### ISSUE TITLE
Page side navigation not scrollable and buttons are hidden.

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#1004]
The Page navigation side navigation is currently not scrollable and tend to hide the buttons when on smaller screens.

<img width="138" alt="image" src="https://user-images.githubusercontent.com/27733432/181100858-2d7c0172-7001-45d1-a678-914136c3ad24.png">
we should ensure we use a list scroll.

**Comment by dreacot** [comment]
we could as well get rid of the titles and leave just the icon when the drawer is minimized, that would give a smaller surface area

**Comment by JustinBeBoy** [comment]
> we could as well get rid of the titles and leave just the icon when the drawer is minimized, that would give a smaller surface area

I believe it is a great idea
