### ISSUE TITLE
Staking window password input field does not handle 'return'

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#1005]
Pressing return to enter a password on the staking window will cause a newline instead of submitting the modal form.

<img width="357" alt="Screen Shot 2022-06-24 at 4 47 45 PM" src="https://user-images.githubusercontent.com/66281245/175749268-2d2e6995-81c5-41b2-bfa0-eb37aa01dc07.png">

**Comment by Sirmorrison** [comment]
resolved by 981
