### ISSUE TITLE
App crashes when spending password change is interrupted

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#1006]
GoDcr crashes when I interrupt changing my password

Reproduction steps:
- Go to wallet settings page 
- Click on "Spending password" 
- Enter your current spending password 
- Cancel on the next step

Video replication steps from my machine 
https://streamable.com/apwe4n

**Comment by dreacot** [comment]
seems related to https://github.com/planetdecred/godcr/issues/1003

**Comment by upright39** [comment]
> Video replication steps from my machine
https://streamable.com/apwe4n

@devchoplife. I am looking for a good first issue to fix. I've tried to reproduce this but it's not reproducible. Do you still see this? 
Btw, I notice the design in your example repro clip is not the same with the current design on master.

**Comment by devchoplife** [comment]
> > Video replication steps from my machine
> > https://streamable.com/apwe4n
> 
> @devchoplife. I am looking for a good first issue to fix. I've tried to reproduce this but it's not reproducible. Do you still see this? Btw, I notice the design in your example repro clip is not the same with the current design on master.

This issue was abandoned due to the change in the UI and has since been resolved
