### ISSUE TITLE
how to use go1.16

### ISSUE THREAD

**Issue by xiaoshengduan** [planetdecred/godcr#1015]
How to support go1.16, the latest versions of gioui all require go1.17, but my project can only use go1.16

D:\WWW\go\gio-godcr-master>go build
# gioui.org/internal/byteslice
C:\Users\admin\go\pkg\mod\gioui.org@v0.0.0-20220601100144-a896a467ecae\internal\byteslice\byteslice.go:16:9: undefined: unsafe.Slice
C:\Users\admin\go\pkg\mod\gioui.org@v0.0.0-20220601100144-a896a467ecae\internal\byteslice\byteslice.go:26:9: undefined: unsafe.Slice
C:\Users\admin\go\pkg\mod\gioui.org@v0.0.0-20220601100144-a896a467ecae\internal\byteslice\byteslice.go:34:9: undefined: unsafe.Slice
note: module requires Go 1.17
# github.com/gioui/uax/segment
C:\Users\admin\go\pkg\mod\github.com\gioui\uax@v0.2.1-0.20220325163150-e3d987515a12\segment\segment.go:275:16: undefined: math.MaxInt
C:\Users\admin\go\pkg\mod\github.com\gioui\uax@v0.2.1-0.20220325163150-e3d987515a12\segment\segment.go:468:14: undefined: math.MaxInt
C:\Users\admin\go\pkg\mod\github.com\gioui\uax@v0.2.1-0.20220325163150-e3d987515a12\segment\segment.go:602:13: undefined: math.MaxInt
# gioui.org/gpu/internal/d3d11
C:\Users\admin\go\pkg\mod\gioui.org@v0.0.0-20220601100144-a896a467ecae\gpu\internal\d3d11\d3d11_windows.go:852:9: undefined: unsafe.Slice
note: module requires Go 1.17

**Comment by Sirmorrison** [comment]
This issue is not so clear.
kindly provide some more context.

**Comment by Sirmorrison** [comment]
issue is stalled and redundant.
