### ISSUE TITLE
Godcr crashes after opening wallets

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#1030]
When I launch godcr, it crashes almost immediately. 
I do not understand the issue yet hence I cannot provide replication steps. 
Video link
++++++++++++++++++++
https://streamable.com/7crtmc

Crash Log
+++++++++++++++++++++
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1231cc8]

goroutine 55 [running]:
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).UnlockWalletForSyncing(0xc002c4bf40, 0xc0001ec960)
	/home/devchoplife/GitRepos/godcr/ui/page/components/wallet_selector.go:474 +0x1c8
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).startSyncing(0xc002c4bf40)
	/home/devchoplife/GitRepos/godcr/ui/page/components/wallet_selector.go:439 +0x89
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).Expose(0xc002c4bf40, {0x1db9098, 0xc0063ff040})
	/home/devchoplife/GitRepos/godcr/ui/page/components/wallet_selector.go:70 +0xd7
github.com/planetdecred/godcr/ui/page.(*WalletDexServerSelector).OnNavigatedTo(0xc000234cc0)
	/home/devchoplife/GitRepos/godcr/ui/page/wallet_dex_selector_page.go:72 +0x6d
github.com/planetdecred/godcr/app.(*PageStack).Reset(0xc00052efc0, {0xc00284f770, 0x1, 0x1})
	/home/devchoplife/GitRepos/godcr/app/pagestack.go:153 +0x112
github.com/planetdecred/godcr/app.(*SimpleWindowNavigator).ClearStackAndDisplay(0xc00052eff0, {0x1dc2770, 0xc000234cc0})
	/home/devchoplife/GitRepos/godcr/app/window.go:84 +0x8f
github.com/planetdecred/godcr/ui/page.(*startPage).openWallets(0xc000e45500, {0x0, 0xc000236d00})
	/home/devchoplife/GitRepos/godcr/ui/page/start_page.go:104 +0x16e
created by github.com/planetdecred/godcr/ui/page.(*startPage).OnNavigatedTo
	/home/devchoplife/GitRepos/godcr/ui/page/start_page.go:59 +0xd1

**Comment by Sirmorrison** [comment]
This has been resolved by PR #1048
