### ISSUE TITLE
nil pointer dereference with wallet hex restore

### ISSUE THREAD

**Issue by raedah** [planetdecred/godcr#1034]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x124d53a]

goroutine 106517 [running]:
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).UnlockWalletForSyncing(0xc0038c2000, 0xc005ac21e0)
        /home/user/code/godcr/ui/page/components/wallet_selector.go:474 +0x1fa
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).startSyncing(0xc0038c2000)
        /home/user/code/godcr/ui/page/components/wallet_selector.go:439 +0x89
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).Expose(0xc0038c2000, {0x1ddf078?, 0xc003a68b00?})
        /home/user/code/godcr/ui/page/components/wallet_selector.go:70 +0xd7
github.com/planetdecred/godcr/ui/page.(*WalletDexServerSelector).OnNavigatedTo(0xc005e54180)
        /home/user/code/godcr/ui/page/wallet_dex_selector_page.go:72 +0x6d
github.com/planetdecred/godcr/app.(*PageStack).Reset(0xc001f766c0, {0xc005dd0240, 0x1, 0x1})
        /home/user/code/godcr/app/pagestack.go:153 +0x112
github.com/planetdecred/godcr/app.(*SimpleWindowNavigator).ClearStackAndDisplay(0xc001f766f0, {0x1de32e8, 0xc005e54180})
        /home/user/code/godcr/app/window.go:84 +0x8f
github.com/planetdecred/godcr/ui/page.(*CreateWallet).handlerWalletDexServerSelectorCallBacks(0xc00215b100)
        /home/user/code/godcr/ui/page/wallet_setup_page.go:492 +0x9f
github.com/planetdecred/godcr/ui/page.(*CreateWallet).HandleUserInteractions.func3()
        /home/user/code/godcr/ui/page/wallet_setup_page.go:451 +0x1d
github.com/planetdecred/godcr/ui/page/info.(*Restore).showHexRestoreModal.func1.1.2.1()
        /home/user/code/godcr/ui/page/info/restore_page.go:256 +0x12d
created by github.com/planetdecred/godcr/ui/page/info.(*Restore).showHexRestoreModal.func1.1.2
        /home/user/code/godcr/ui/page/info/restore_page.go:243 +0x125

**Comment by Sirmorrison** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x4dc7e88]

goroutine 6116 [running]:
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).UnlockWalletForSyncing(0xc005cf4000, 0xc00bea83c0)
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/components/wallet_selector.go:474 +0x1c8
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).startSyncing(0xc005cf4000)
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/components/wallet_selector.go:439 +0x89
github.com/planetdecred/godcr/ui/page/components.(*WalletSelector).Expose(0xc005cf4000, {0x58db558, 0xc0037e3e80})
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/components/wallet_selector.go:70 +0xd7
github.com/planetdecred/godcr/ui/page.(*WalletDexServerSelector).OnNavigatedTo(0xc0058a7020)
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/wallet_dex_selector_page.go:72 +0x6d
github.com/planetdecred/godcr/app.(*PageStack).Reset(0xc00002c3f0, {0xc021844200, 0x1, 0x1})
	/Users/sirmorrison/Desktop/go projects/godcr-gio/app/pagestack.go:153 +0x112
github.com/planetdecred/godcr/app.(*SimpleWindowNavigator).ClearStackAndDisplay(0xc00002c720, {0x58e4b30, 0xc0058a7020})
	/Users/sirmorrison/Desktop/go projects/godcr-gio/app/window.go:84 +0x8f
github.com/planetdecred/godcr/ui/page.(*CreateWallet).handlerWalletDexServerSelectorCallBacks(0xc0020ef100)
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/wallet_setup_page.go:492 +0x9f
github.com/planetdecred/godcr/ui/page.(*CreateWallet).HandleUserInteractions.func3()
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/wallet_setup_page.go:451 +0x1d
github.com/planetdecred/godcr/ui/page/info.(*Restore).showHexRestoreModal.func1.1.2.1()
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/info/restore_page.go:256 +0x118
created by github.com/planetdecred/godcr/ui/page/info.(*Restore).showHexRestoreModal.func1.1.2
	/Users/sirmorrison/Desktop/go projects/godcr-gio/ui/page/info/restore_page.go:243 +0x128

reproduced @crux25
