### ISSUE TITLE
Seeking help

### ISSUE THREAD

**Issue by Esword618** [planetdecred/godcr#1046]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/73058062/186449956-aabadecd-59ab-438a-80ff-4508a4ea4248.png">
I want to implement a child window like popup in the picture above, but after reading the way it is implemented from godcr and trying it myself, I still have errors, I'm a bit overwhelmed, I've been blocked by this for ages, can you help me with my code!!!

Here is my code.

```
import (
	"image"
	"image/color"
	"log"

	"gioui.org/app"
	"gioui.org/io/system"
	"gioui.org/layout"
	"gioui.org/op"
	"gioui.org/op/clip"
	"gioui.org/op/paint"
	"gioui.org/unit"
	"gioui.org/widget"
	"gioui.org/widget/material"

	"gioui.org/font/gofont"
	"gioui.org/x/haptic"
)

var buzzer *haptic.Buzzer

func main() {
	go func() {
		w := app.NewWindow()
		if err := loop(w); err != nil {
			log.Fatal(err)
		}
	}()
	app.Main()
}

func loop(w *app.Window) error {
	th := material.NewTheme(gofont.Collection())
	btn := widget.Clickable{}
	buzzer = haptic.NewBuzzer(w)
	var ops op.Ops
	for {
		select {
		case e := <-w.Events():
			switch e := e.(type) {
			case system.DestroyEvent:
				return e.Err
			case system.FrameEvent:
				if btn.Clicked() {
					buzzer.Buzz()
				}
				gtx := layout.NewContext(&ops, e)

				layout.Flex{Axis: layout.Vertical}.Layout(gtx,
					layout.Rigid(func(gtx layout.Context) layout.Dimensions {
						return material.Button(th, &btn, "Login").Layout(gtx)
					}),
					layout.Rigid(func(gtx layout.Context) layout.Dimensions {
						// var clickable *Clickable
						// clickable = new(Clickable)
						return DDDD().Layout(gtx, func(gtx layout.Context) layout.Dimensions {
							return layout.Flex{Axis: layout.Vertical}.Layout(gtx,
								layout.Rigid(func(gtx layout.Context) layout.Dimensions {
									return material.Button(th, &btn, "Login1").Layout(gtx)
								}),
							)
						})
					}),
				)
				e.Frame(gtx.Ops)

			}
		case err := <-buzzer.Errors():
			if err != nil {
				log.Printf("buzzer error: %v", err)
			}
		}
	}
}

func DDDD() *Clickable {
	return &Clickable{}
}

type ClickableStyle struct {
	Color      color.NRGBA
	HoverColor color.NRGBA
}

type CornerRadius struct {
	TopLeft     int
	TopRight    int
	BottomRight int
	BottomLeft  int
}
type Clickable struct {
	button    *widget.Clickable
	style     *ClickableStyle
	Hoverable bool
	Radius    CornerRadius
	isEnabled bool
}

type (
	C = layout.Context
	D = layout.Dimensions
)

func (cl *Clickable) Layout(gtx C, w layout.Widget) D {
	return cl.button.Layout(gtx, func(gtx layout.Context) layout.Dimensions {
		return layout.Stack{}.Layout(gtx,
			layout.Expanded(func(gtx layout.Context) layout.Dimensions {
				tr := gtx.Dp(unit.Dp(cl.Radius.TopRight))
				tl := gtx.Dp(unit.Dp(cl.Radius.TopLeft))
				br := gtx.Dp(unit.Dp(cl.Radius.BottomRight))
				bl := gtx.Dp(unit.Dp(cl.Radius.BottomLeft))
				defer clip.RRect{
					Rect: image.Rectangle{Max: image.Point{
						X: gtx.Constraints.Min.X,
						Y: gtx.Constraints.Min.Y,
					}},
					NW: tl, NE: tr, SE: br, SW: bl,
				}.Push(gtx.Ops).Pop()
				clip.Rect{Max: gtx.Constraints.Min}.Push(gtx.Ops).Pop()

				if cl.Hoverable && cl.button.Hovered() {
					paint.Fill(gtx.Ops, cl.style.HoverColor)
				}

				// for _, c := range cl.button.History() {
				// 	drawInk(gtx, c, cl.style.Color)
				// }
				return layout.Dimensions{Size: gtx.Constraints.Min}
			}),
			layout.Stacked(w),
		)
	})
}
```

**Comment by devchoplife** [comment]
> <img alt="image" width="384" src="https://user-images.githubusercontent.com/73058062/186449956-aabadecd-59ab-438a-80ff-4508a4ea4248.png">
> 
> I want to implement a child window like popup in the picture above, but after reading the way it is implemented from godcr and trying it myself, I still have errors, I'm a bit overwhelmed, I've been blocked by this for ages, can you help me with my code!!!
> Here is my code.
> 
> ```
> import (
> 	"image"
> 	"image/color"
> 	"log"
> 
> 	"gioui.org/app"
> 	"gioui.org/io/system"
> 	"gioui.org/layout"
> 	"gioui.org/op"
> 	"gioui.org/op/clip"
> 	"gioui.org/op/paint"
> 	"gioui.org/unit"
> 	"gioui.org/widget"
> 	"gioui.org/widget/material"
> 
> 	"gioui.org/font/gofont"
> 	"gioui.org/x/haptic"
> )
> 
> var buzzer *haptic.Buzzer
> 
> func main() {
> 	go func() {
> 		w := app.NewWindow()
> 		if err := loop(w); err != nil {
> 			log.Fatal(err)
> 		}
> 	}()
> 	app.Main()
> }
> 
> func loop(w *app.Window) error {
> 	th := material.NewTheme(gofont.Collection())
> 	btn := widget.Clickable{}
> 	buzzer = haptic.NewBuzzer(w)
> 	var ops op.Ops
> 	for {
> 		select {
> 		case e := <-w.Events():
> 			switch e := e.(type) {
> 			case system.DestroyEvent:
> 				return e.Err
> 			case system.FrameEvent:
> 				if btn.Clicked() {
> 					buzzer.Buzz()
> 				}
> 				gtx := layout.NewContext(&ops, e)
> 
> 				layout.Flex{Axis: layout.Vertical}.Layout(gtx,
> 					layout.Rigid(func(gtx layout.Context) layout.Dimensions {
> 						return material.Button(th, &btn, "Login").Layout(gtx)
> 					}),
> 					layout.Rigid(func(gtx layout.Context) layout.Dimensions {
> 						// var clickable *Clickable
> 						// clickable = new(Clickable)
> 						return DDDD().Layout(gtx, func(gtx layout.Context) layout.Dimensions {
> 							return layout.Flex{Axis: layout.Vertical}.Layout(gtx,
> 								layout.Rigid(func(gtx layout.Context) layout.Dimensions {
> 									return material.Button(th, &btn, "Login1").Layout(gtx)
> 								}),
> 							)
> 						})
> 					}),
> 				)
> 				e.Frame(gtx.Ops)
> 
> 			}
> 		case err := <-buzzer.Errors():
> 			if err != nil {
> 				log.Printf("buzzer error: %v", err)
> 			}
> 		}
> 	}
> }
> 
> func DDDD() *Clickable {
> 	return &Clickable{}
> }
> 
> type ClickableStyle struct {
> 	Color      color.NRGBA
> 	HoverColor color.NRGBA
> }
> 
> type CornerRadius struct {
> 	TopLeft     int
> 	TopRight    int
> 	BottomRight int
> 	BottomLeft  int
> }
> type Clickable struct {
> 	button    *widget.Clickable
> 	style     *ClickableStyle
> 	Hoverable bool
> 	Radius    CornerRadius
> 	isEnabled bool
> }
> 
> type (
> 	C = layout.Context
> 	D = layout.Dimensions
> )
> 
> func (cl *Clickable) Layout(gtx C, w layout.Widget) D {
> 	return cl.button.Layout(gtx, func(gtx layout.Context) layout.Dimensions {
> 		return layout.Stack{}.Layout(gtx,
> 			layout.Expanded(func(gtx layout.Context) layout.Dimensions {
> 				tr := gtx.Dp(unit.Dp(cl.Radius.TopRight))
> 				tl := gtx.Dp(unit.Dp(cl.Radius.TopLeft))
> 				br := gtx.Dp(unit.Dp(cl.Radius.BottomRight))
> 				bl := gtx.Dp(unit.Dp(cl.Radius.BottomLeft))
> 				defer clip.RRect{
> 					Rect: image.Rectangle{Max: image.Point{
> 						X: gtx.Constraints.Min.X,
> 						Y: gtx.Constraints.Min.Y,
> 					}},
> 					NW: tl, NE: tr, SE: br, SW: bl,
> 				}.Push(gtx.Ops).Pop()
> 				clip.Rect{Max: gtx.Constraints.Min}.Push(gtx.Ops).Pop()
> 
> 				if cl.Hoverable && cl.button.Hovered() {
> 					paint.Fill(gtx.Ops, cl.style.HoverColor)
> 				}
> 
> 				// for _, c := range cl.button.History() {
> 				// 	drawInk(gtx, c, cl.style.Color)
> 				// }
> 				return layout.Dimensions{Size: gtx.Constraints.Min}
> 			}),
> 			layout.Stacked(w),
> 		)
> 	})
> }
> ```

What errors do you get?

**Comment by Sirmorrison** [comment]
SO the screenshot is a combination of features. first the decredmaterial modal. and the info modal widgets.
I believe this is a good starting point. Look through the `decredmaterial/modal.go` file implementation and that on the `modal/info_modal.go` file

**Comment by Esword618** [comment]
ok,thanks
