### ISSUE TITLE
add back button to sign and verify message pages

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#111]
### Can the feature be described as a User story?
When I open page the sign message or verify message pages from the wallet page, I should see a back button I can click that takes me back to both pages.

**Comment by Sirmorrison** [comment]
this feature may need the subpage feature on the wallet page  pr to be merged.

**Comment by oshorefueled** [comment]
> this feature may need the subpage feature on the wallet page pr to be merged.

why would a back button need a sub page feature? All that's needed is a button on each of those pages that navigates back to the wallet page when it's clicked. A similar implementation is on the transaction detail page.

**Comment by song50119** [comment]
When at wallet page assume we have two cases:
1. Click to verify page  -> Click Tab navigator -> Now we are on the wallet page
2. Click to verify page -> Click Tab navigator -> `Should we on the verify page?`
If 2 we should have sub page, right?

**Comment by Sirmorrison** [comment]
> why would a back button need a sub page feature? All that's needed is a button on each of those pages that navigates back to the wallet page when it's clicked. A similar implementation is on the transaction detail page.

what i meant to say was this feature is already added with the wallet page i am currently working on since these pages are sub pages of the wallet page.
<img width="497" alt="image" src="https://user-images.githubusercontent.com/27733432/82718383-1e91f500-9c9a-11ea-9ec4-8b73115e827f.png">
