### ISSUE TITLE
amount in USD

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#142]
### Can the feature be described as a User story?
When I'm on send page and I have sufficient balance, 
* I should be able to switch between inputting the amount in DCR and USD. 
* See what currency I'm sending in USD or DCR

### Additional context
Amount input on mobile mock up
<img width="228" alt="Screenshot 2020-06-08 at 7 45 04 PM" src="https://user-images.githubusercontent.com/15804688/84068386-c6106680-a9c0-11ea-98a4-df0a8329fd64.png">

**Comment by song50119** [comment]
This is can close?
