### ISSUE TITLE
make checkbox icon modifiable

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#168]
### describe the feature
Currently, the checkbox only supports one design pattern, the box and the check in the middle. However, the mobile design uses a circle with a check on the seed back up page. Our seed back up page should be similar to the mobile. 

### Additional context
Mobile Mockup 
![Screenshot 2020-06-30 at 12 03 21 AM](https://user-images.githubusercontent.com/15804688/86064703-af13e000-ba65-11ea-8c7b-2def93101539.png)

![Screenshot 2020-06-30 at 12 03 41 AM](https://user-images.githubusercontent.com/15804688/86064711-b2a76700-ba65-11ea-997c-e914836a1b59.png)

Godcr Seed backup page
<img width="600" alt="Screenshot 2020-06-30 at 12 08 48 AM" src="https://user-images.githubusercontent.com/15804688/86064821-fac68980-ba65-11ea-9382-b25c67bb0e85.png">

**Comment by oshorefueled** [comment]
A patch has been submitted to have icons changeable upstream https://lists.sr.ht/~eliasnaur/gio-patches/%3C43DE2453-E9E2-421C-A235-263350AB4CEE%40icloud.com%3E

**Comment by ghost** [comment]
This has been in stasis for a few weeks now, I have written several custom checkbox widgets already. If a temporary version were to be put in would that be desired? The checkbox widget is extremely simple, probably second to the button in complexity.
