### ISSUE TITLE
custom list layout with scrollbar

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#217]
The current Gioui version has a bug with the list layout. It can be glitchy when trying to scroll through a list containing widgets that also have scroll properties such as the editor widget. A work around for this would be to create a custom list layout with a scrollbar. A scroll bar would be needed anyway as not every user might have scroll gestures supported on their machine.

related issue #204

**Comment by ghost** [comment]
This is a pretty big job. The list layout is very kludgy, it works ok on touchscreens but tends to be, as you say, reading scroll gestures in the text widgets and seeming to not work. I started work on something that created a slice of widgets that pre-render so their height was known. Constraining the exact requirements, such as for only allowing items to take up a consistent vertical space would let you put a better scroller in there. There is one such existing minimally functional one in my previous project but it doesn't handle varying height elements.

I don't know how many custom widgets have already been created but for anything but the most simple layouts, they basically are mandatory at this point in the development of Gio.

**Comment by oshorefueled** [comment]
I don't think it's that "big" of a job. I'm not suggesting that the list layout code be rewritten to add the scrollbar. What I'm suggesting is an extension of the already existing list layout. The slider widget already implements dragging a widget horizontally. The list widget has an exported "Scroll" field that supports programmatically scrolling the list. With that, It shouldn't be too difficult creating a scrollbar using the existing list layout.

**Comment by ghost** [comment]
If the list elements can be kept a consistent size on their scrolling axis it's a very easy job. If there is text involved that will additionally require a ellipsising function on them, or they can just be rendered with a clip. Eliminating the interaction of scrollable elements in the list can be achieved by putting a hitbox over top that overrides them if a 'hit the end' trigger is added.

**Comment by ghost** [comment]
in case anyone was curious I finally wrote a scrollbar addition to a List: https://github.com/p9c/pod/blob/master/pkg/gui/p9/list.go

Not quite quite finished yet but fully functional. I am adding the logic to not render the bar when it's empty (requires a second layout pass if content does not overflow), changing the page up/down button areas to use a custom event processor (like the dragger) so they don't have the 'ink' animation.
