### ISSUE TITLE
Can't copy receiving address in FreeBSD

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#221]
Hello,

The copy address button does say address copied, but there's nothing in the clipboard to paste afterwards.

Thanks

**Comment by ghost** [comment]
It may be necessary to add a different clipboard handler for FreeBSD, I recall when I was working on another project my colleague at first also had some issues, maybe look for an alternative clipboard library separately for freebsd? https://github.com/p9c/pod has a mostly complete but sorta shabby looking wallet app that has fully functional clipboard on FreeBSD as the developer who wrote it runs a FreeBSD dev machine.

**Comment by song50119** [comment]
Solved by install xclip, wl-clipboard, xsel or Termux:API add-on for OS

**Comment by oshorefueled** [comment]
This would be resolved with #251
