### ISSUE TITLE
Fix broken backup seed page

### ISSUE THREAD

**Issue by ghost** [planetdecred/godcr#230]
Currently after you click the backup seed page it opens a giant half-screen box and all the sidebar and navigation disappears, and nothing happens when the 'view seed phrase' button is clicked. I will start with this as it has the smallest scope of all the visibly needed pages to be fixed.

**Comment by oshorefueled** [comment]
The backup seed page seems to have been broken after the major Gio update version. 
Below are screenshots of its UI before the update

<img width="699" alt="Screenshot 2020-08-10 at 11 12 09" src="https://user-images.githubusercontent.com/15804688/89772880-b6191e00-dafa-11ea-95f9-f51deec8311e.png">

<img width="600" alt="Screenshot 2020-08-10 at 11 12 25" src="https://user-images.githubusercontent.com/15804688/89772885-baddd200-dafa-11ea-906d-18794cc04a91.png">

<img width="600" alt="Screenshot 2020-08-10 at 11 12 40" src="https://user-images.githubusercontent.com/15804688/89772898-c03b1c80-dafa-11ea-945e-f437e2e5e31d.png">

**Comment by ghost** [comment]
The issue relates to something related to the Stack widget and the positioning by the constraints, the go forward button is not being padded by the inset properly and it's filling the whole window now. I think these are operating on the wrong context, from an outer closure. Or something.

I think this layout is overly complicated, you should not use stacked with things that aren't overlaid (eg without modals, toasters) I will change it to use a mix of flexed and rigid and that should fix the problem, I will aim to match the layout that appears in the above screenshots.
