### ISSUE TITLE
Add automatic connect option beside connect/cancel button 

### ISSUE THREAD

**Issue by ghost** [planetdecred/godcr#231]
For testing purposes, it is inconvenient to have to manually click it every time it starts up to start syncing. I propose to add a button next to the connect/cancel button to automatically switch the sync on if the new 'automatically connect' checkbox is selected.

**Comment by oshorefueled** [comment]
how often do you restart when testing?

**Comment by ghost** [comment]
I am a go programmer. it might be a minute it might be an hour but if I am working on a widget that depends on up to date data it's going to slow things down irritatingly. If the option is there you don't have to turn it on if you don't want to, but the reverse is not true.

It is the simplest useful feature I can start with to warm up.

I may have missed something, but also, I see there is no UI configuration system. I have written several custom, automatically persisting settings like this already, and I think it would be helpful basis to several other features that will be added later.

**Comment by oshorefueled** [comment]
I'm not sure what widget you plan to work on right now that needs this but creating test features in anticipation of uncertain future implementations doesn't sound very practical. Adding an "automatic sync" on start up isn't a bad idea, it could be useful to a user. Probably better on a settings page than on the overview page as a checkbox but adding a feature that's not needed currently isn't logical.
