### ISSUE TITLE
add proposals list page

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#236]
A proposals page should be added. When I open the proposals list page, I should see a list of proposals from the politeia server. 

Below is a layout for the page to be modelled after. 
![proposals view list](https://user-images.githubusercontent.com/15804688/90375558-03ead480-e06d-11ea-86dd-419aab2e5eb5.jpg)

**Comment by xaur** [comment]
I suggest aggresively caching proposals and their metadata (published date, edited date, status, etc) to minimize traffic to a central server. It even allows to fire up godcr and read proposals offline.

I would go as far as add the "update" button to grab the data manually and update the local proposal database.

This requires some sync logic to fetch only those proposal revisions that are missing.

Storing hundreds of markdown files will take just a few megabytes.
