### ISSUE TITLE
send page content changes alignment on scroll

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#237]
the send page changes alignment from center to left alignment when it is scrolled on a smaller window size. 

Below is a short recording showing this behaviour:
![send-page-transition-bug](https://user-images.githubusercontent.com/15804688/90377806-6c878080-e070-11ea-90b5-3e9e2dc1cde5.gif)

**Comment by Sirmorrison** [comment]
this issue was resolved in #223
