### ISSUE TITLE
bug in `toMax`

### ISSUE THREAD

**Issue by egonelbre** [planetdecred/godcr#294]
I noticed a bug in https://github.com/planetdecred/godcr/blob/master/ui/page.go#L748:

```
func toMax(gtx layout.Context) {
	gtx.Constraints.Min.X = gtx.Constraints.Max.X
	gtx.Constraints.Min.Y = gtx.Constraints.Max.Y
}
```

That func doesn't have an impact to layout.Context.

**Comment by oshorefueled** [comment]
Thank you for pointing that out. The function will be removed on a code cleanup.
