### ISSUE TITLE
implement currency conversion option on settings page

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#351]
Currently a currency conversion option can't be selected from the settings page. The selected currency conversion endpoint is used to convert between DCR and USD on the send page. This should be implemented as in the mockup below. 

![Screenshot 2021-03-25 at 10 22 03](https://user-images.githubusercontent.com/15804688/112449711-fb215600-8d53-11eb-9d31-bd1690943bc8.png)

**Comment by JustinBeBoy** [comment]
I have tested,  currency conversion option can be selected from the settings page
![xxxxxx](https://user-images.githubusercontent.com/19331824/112752245-3ba2fd00-8ffc-11eb-9435-08d9078f5d7e.PNG)

**Comment by Sirmorrison** [comment]
This was implemented with the send page @oshorefueled .
