### ISSUE TITLE
select account on send page and receive page

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#368]
Currently, I can only select accounts from the first and second wallet on the account selector widget. I have 4 wallets created and when I select an account from the third or fourth wallet, the second wallet gets selected on the account selector widget. The video recording below shows this 

Scrolling is also difficult on the account selector. Not just the account selector though but the app where there are nested lists or scrollable widgets. The scroll issue was fixed in this gio version and https://git.sr.ht/~eliasnaur/gio/commit/5e1a662b940dd1177395e95999980f97c000d2c4. The gio version should be updated to the latest version to take advantage of recent bug fixes and features. 

![account-selector-gif](https://user-images.githubusercontent.com/15804688/114487823-2935df80-9c08-11eb-83f4-b56420278056.gif)

**Comment by Sirmorrison** [comment]
This issue has been resolved in PR 353... The only issue when selecting wallets is when its a mixed account.. They keep getting skipped been trying to figure out why but nothing yet.

**Comment by oshorefueled** [comment]
another issue #378 has been created to fix the scrolling issue.
