### ISSUE TITLE
godcr slows down while syncing

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#377]
when syncing a new wallet, the user interface seems to lag. It is understood that syncing a new wallet can be CPU intensive, however, the UI shouldn't lag when this is going on.

Machine Specifications
OS: MacOs 
Processor: 2.4 GHz Quad-Cor Intel Core i5
Memory:  8gb

**Comment by song50119** [comment]
<img width="430" alt="Screen Shot 2021-04-23 at 22 50 13" src="https://user-images.githubusercontent.com/9800579/115897143-509d6f80-a486-11eb-818d-6c0b834a23c7.png">

I do profile track and see the high pressure on CPU, as Image show `(*addrFinder).filter` and `(*filter).MatchAny` during sync
