### ISSUE TITLE
can't disconnect from the decred network

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#385]
sometimes clicking the disconnect button doesn't close the connection with the decred network. It seems to disconnect and then connect back almost immediately.

![connect-bug](https://user-images.githubusercontent.com/15804688/116125546-8bd5b380-a6bd-11eb-8acb-0d11b7f78d60.gif)

**Comment by oshorefueled** [comment]
The bug occurs randomly and the steps to reproduce it hasn't be defined.

**Comment by dreacot** [comment]
resolved by https://github.com/planetdecred/godcr/pull/731
