### ISSUE TITLE
enter button should submit password

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#405]
Currently after inputting a password in a password field, pressing the enter key adds a new character in the input field. It should instead perform the equivalent action of clicking the confirm button.

![Screenshot 2021-05-12 at 12 57 48](https://user-images.githubusercontent.com/15804688/117972146-a9905300-b322-11eb-9ad1-5598422e863d.png)

**Comment by Sirmorrison** [comment]
I think we can extend this functionality beyond submit password, to create wallet, import watch only wallet etc... basically, what i mean is when the enter btn is pressed, it should execute the confirm part of any modal action.
