### ISSUE TITLE
wrong number of No votes on approved proposal

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#427]
The below screenshot shows an approved proposal with 0 No votes. However, the proposal on proposals.decred.org shows the proposal with 288 votes.

<img width="745" alt="Screenshot 2021-05-20 at 21 30 58" src="https://user-images.githubusercontent.com/15804688/119044912-b06a3600-b9b2-11eb-9b85-344e0400e1d0.png">

**Comment by Sirmorrison** [comment]
We will need to confirm that this issue is no caused by the current version of dcrlibwallet we are currently using and not on godcr side.

**Comment by beansgum** [comment]
https://github.com/planetdecred/godcr/pull/433 resolves this by upgrading to dcrlibwallet v1.6.0
