### ISSUE TITLE
loader doesn't stop displaying on confirm modal

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#431]
The loader doesn't stop displaying on the send modal when a wrong password is submitted. It should revert back to the send button when there's an error on the modal. The same thing occurs when the send button is clicked and godcr is connected to the decred network.

<img width="796" alt="Screenshot 2021-05-23 at 23 51 22" src="https://user-images.githubusercontent.com/15804688/119279231-3e982380-bc22-11eb-8270-eb59caaacf97.png">

**Comment by Sirmorrison** [comment]
This issue should be resolved when Pr #414 is merged.
I had this issue resolved while implementing the submit functionality with the enter button.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/27733432/119407551-4916f380-bcdc-11eb-9e7d-605263e2ec5b.png">

**Comment by Sirmorrison** [comment]
this issue still occurs but not on the confirmation modal. It occurs on the modal templates when there is an error.
I am working to resolve this.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/27733432/119706204-91a3ed80-be51-11eb-86e8-c5ba54df7bee.png">
