### ISSUE TITLE
crash on initial godcr launch

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#471]
running godcr for the first time causes a crash

Config file (/Users/klinsmann/Library/Application Support/Godcr/godcr.conf) does not exist. Using defaults.
2021-06-16 21:49:08.154 [INF] DLWL: Loaded 0 wallets
2021-06-16 21:49:08.759 [INF] UI: Starting sync
2021-06-16 21:49:08.759 [INF] DLWL: Syncing 0 wallets
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46449ab]

goroutine 55 [running]:
decred.org/dcrwallet/wallet.(*Wallet).BlockLocators(0x0, 0x51150b8, 0xc00011a200, 0x0, 0x0, 0x0, 0x0, 0xffffffff, 0x0, 0x0, ...)
        /Users/klinsmann/go/pkg/mod/decred.org/dcrwallet@v1.6.0-rc4/wallet/wallet.go:1336 +0xab
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).Run(0xc00023cfc0, 0x51150b8, 0xc00011a200, 0x0, 0x0)
        /Users/klinsmann/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.0/spv/sync.go:354 +0x70e
github.com/planetdecred/dcrlibwallet.(*MultiWallet).SpvSync.func1(0xc00023cfc0, 0x51150b8, 0xc00011a200, 0xc000278000)
        /Users/klinsmann/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.0/sync.go:254 +0x49
created by github.com/planetdecred/dcrlibwallet.(*MultiWallet).SpvSync
        /Users/klinsmann/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.0/sync.go:253 +0x705

**Comment by beansgum** [comment]
Fixed by #465
