### ISSUE TITLE
duration till next ticket price

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#480]
add duration till next ticket price as show in the screenshot below
![Screenshot 2021-06-18 at 16 13 50](https://user-images.githubusercontent.com/15804688/122582631-447dfa80-d050-11eb-904b-c9c9d404102d.png)

`See All` in the current implementation should be `See all`. Note the `all` is in all lower case
<img width="568" alt="Screenshot 2021-06-18 at 16 15 00" src="https://user-images.githubusercontent.com/15804688/122582977-ab031880-d050-11eb-871f-73be508bb74a.png">

**Comment by song50119** [comment]
Continue when [this PR](https://github.com/planetdecred/dcrlibwallet/pull/204) get merged
