### ISSUE TITLE
wallet page cleanup

### ISSUE THREAD

**Issue by oshorefueled** [planetdecred/godcr#485]
Sign Message
* Use bold for “clear all” and “Sign message” button texts ( also applies to buttons on the verify message page)
* use grey background for signature text

Verify message
* change error message to “Invalid signature or message” instead of just “Invalid signature”

View property 
* remove navigation to help page

StakeShuffle
* change Privacy title on page to StakeShuffle
* add margin left to “keep this app opened” text
* add message stating “The mixer will automatically stop when unmixed balance are fully mixed.”

**Comment by devchoplife** [comment]
Using Grey background for signature text makes the signature text invisible because signature text is also Grey. 

If background is being set to Grey, the text color has to be changed too
