### ISSUE TITLE
Issue going back to main starting page after opening multiple nested sub pages.

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#497]
I can't go back from the transactions detail page after navigating to the receive page.
To Reproduce

    go to a transaction detail page
    navigate to the receive page
    close the receive page

Trying to click the back button on the transaction detail page doesn't work.
or
   
   from any page, open the receive page, then open the send page and try going back to the first page.

The back button does not respond.

**Comment by beansgum** [comment]
Partly fixed by #492
