### ISSUE TITLE
fix the modal on the SecurityTools page

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#501]
Currently this is what the modal on the SecurityTools page looks like

also clicking the "Got it" button on the modal doesn't dismiss the modal
<img width="799" alt="Screenshot 2021-06-30 at 3 43 04 PM" src="https://user-images.githubusercontent.com/25265396/123980975-dde6ce00-d9b9-11eb-944f-361fd83c0882.png">

This is what it should look like
![Security tools 2 (alert dialog)](https://user-images.githubusercontent.com/25265396/123981569-4b92fa00-d9ba-11eb-999d-e6864ae7ab08.png)

**Comment by devchoplife** [comment]
I tried reproducing the issue and it displayed on my end. This is on master.
 
![Screenshot from 2021-07-02 06-36-17](https://user-images.githubusercontent.com/66803475/124226095-6e2f2b00-db00-11eb-9fec-6d352fed4efc.png)

**Comment by beansgum** [comment]
@devchoplife Same.
