### ISSUE TITLE
update the modal on the VerifyMessage page

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#503]
This is what the current modal on the VerifyMessage page looks like
<img width="800" alt="Screenshot 2021-06-30 at 4 05 33 PM" src="https://user-images.githubusercontent.com/25265396/123984988-01f7de80-d9bd-11eb-9511-a41a2fb4807b.png">

This is what it should look like
![Verify message 2](https://user-images.githubusercontent.com/25265396/123985066-1045fa80-d9bd-11eb-90dd-b14e6b1803fa.png)

**Comment by oshorefueled** [comment]
Currently, gio doesn't have the ability to set text properties within a label. That's what we're trying to achieve with #469

**Comment by oshorefueled** [comment]
<img width="798" alt="Screenshot 2021-07-28 at 18 06 27" src="https://user-images.githubusercontent.com/15804688/127365887-b847b541-8cca-46b7-bdd7-26b18977f7eb.png">
