### ISSUE TITLE
fix margin on the ValidateAddress Page

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#504]
This is how the ValidateAddress page looks
<img width="799" alt="Screenshot 2021-06-30 at 4 08 05 PM" src="https://user-images.githubusercontent.com/25265396/123985401-5c913a80-d9bd-11eb-82dc-67f614f162a0.png">

This is what it should look like

![Validate address 1](https://user-images.githubusercontent.com/25265396/123985993-d4f7fb80-d9bd-11eb-8939-61171e280467.png)

**Comment by beansgum** [comment]
Fixed in https://github.com/planetdecred/godcr/pull/459
