### ISSUE TITLE
Clicking clear all fields on the send page only clears the amount field

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#510]
Clicking clear all fields on the send page only clears the amount field

it should clear the address field as well
<img width="596" alt="Screenshot 2021-06-30 at 4 43 36 PM" src="https://user-images.githubusercontent.com/25265396/123991120-56518d00-d9c2-11eb-9814-0acf719ae0e1.png">

**Comment by beansgum** [comment]
Closed by #524
