### ISSUE TITLE
Dark Mode update

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#568]
- When the "Back up seed phrase" button is clicked on wallet page, "Keep in mind" page shows up, but the text is unreadable in dark mode:

<img src="https://user-images.githubusercontent.com/66803475/130184383-86e0f4a3-0961-4ddc-b4ff-e3fdf1d8a087.png" width="700" />

- On tickets page, when the "Purchase ticket" button is clicked, a modal shows up which has unreadable text and border lines that match the background color:
<img src="https://user-images.githubusercontent.com/66803475/130184672-7ea734ac-61d3-4a5f-ab2e-01ff3dce95dd.png" width="700"/>

- On the modal displayed above, when the "Select VSR" field is clicked, another modal shows up which contains the different VSRs. This modal has unreadable textin dark mode as shown below:
<img src="https://user-images.githubusercontent.com/66803475/130184972-ae837ff9-0066-4124-9255-8c9cf8fc11ed.png" width="700" />

- godcr uses incorrect logo in dark mode

<img src="https://user-images.githubusercontent.com/66803475/134059071-9bcffc0b-67f2-4de8-b92b-3c4a386bfdda.png" width="300" />

The UI should switch to using

<img src="https://user-images.githubusercontent.com/66803475/134059113-9afa3bb0-6135-40df-8505-4d326635b77f.png" width="150" />

this icon instead

**Comment by Sirmorrison** [comment]
Issues relating to dark mode are currently suspended until the first release.
I think its best we disable the button in the mean time.
