### ISSUE TITLE
Unreadable text in dark mode on tickets page 

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#569]
On tickets page, when the "Purchase ticket" button is clicked, a modal shows up which has unreadable text and border lines that match the background color:
![Screenshot from 2021-08-19 22-47-35](https://user-images.githubusercontent.com/66803475/130184672-7ea734ac-61d3-4a5f-ab2e-01ff3dce95dd.png)

On the modal displayed above, when the "Select VSR" field is clicked, another modal shows up which contains the different VSRs. This modal has unreadable textin dark mode as shown below:
![Screenshot from 2021-08-19 22-53-00](https://user-images.githubusercontent.com/66803475/130184972-ae837ff9-0066-4124-9255-8c9cf8fc11ed.png)

**Comment by Sirmorrison** [comment]
This can be merged into #568. same comment applies.
Dark mode is currently on hold till after the first release as mentioned by @raedah

**Comment by devchoplife** [comment]
Merged into #568
