### ISSUE TITLE
Remove timeframe of completion from  expired tickets

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#570]
Currently, on the ticket page, the expired tickets have a time frame for completion.
<img width="788" alt="image" src="https://user-images.githubusercontent.com/27733432/130195171-49829c8e-6358-475f-9e9d-88f5b8d6f437.png">

however, the expired tickets should look like this.
<img width="624" alt="image" src="https://user-images.githubusercontent.com/27733432/130195034-94ea7359-bc7a-4ecc-80d4-ec06064f3577.png">

**Comment by beansgum** [comment]
Should be fixed by #567
