### ISSUE TITLE
Side and Top page Navigation button does not display Ripple effect

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#573]
The highlight ripple animation doesn't show when the side and top page nav buttons are pressed, unlike other clickables.

* To demonstrate the effected we are talking about, go to the transactions page, press and hold on a transaction. This should display a dark overlay effect.

from troubleshooting done, this is as a result of the card used to show the selected page. it overlays on the button therefore hiding the button effect.

PR #563 should fix the issue with the card display.

**Comment by devchoplife** [comment]
#563  fixes this but I noticed the overlay effect does not stay within the borders of each transaction 
See below:
![Screenshot from 2021-08-21 15-49-03](https://user-images.githubusercontent.com/66803475/130325813-a8137ce2-9449-48e4-9e96-250e8ad912e5.png)

**Comment by Sirmorrison** [comment]
#563 only offers a solution not the fix. Also the issue with the overlay has been resolved in #559.
