### ISSUE TITLE
"Clear all fields" position on Send page

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#576]
On Send page, when the options button is clicked, "Clear all fields" appears but the position is not correct.
See image below:
![Screenshot from 2021-08-21 19-01-13](https://user-images.githubusercontent.com/66803475/130331253-2d0359d4-7f31-4c46-aeb3-2a2122b962b9.png)

**Comment by Sirmorrison** [comment]
This issue only occurs when the App is displayed in full screen not the default view.. on the default view, it displays correctly.
