### ISSUE TITLE
Newly created account not displaying on wallet page until manual reload

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#597]
On the wallet page, when a new account is created under a particular wallet, or when account mixer is setup, the newly created accounts do not display on the UI until the application is restarted.

The expected behavior is to have the accounts display immediately they are created.

**Comment by oshorefueled** [comment]
From my tests, it seems reloading the page by navigating to another page and navigating back to the wallet page displays the created account. I don't think the app needs to be restarted to reproduce the bug. Also, the issue also occurs for created wallets.
