### ISSUE TITLE
Proposals page nav width

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#600]
When the proposals page is displayed in full screen, the proposal navigation tabs are expanded and there is currently too much whitespace.
![image](https://user-images.githubusercontent.com/27733432/131867629-3cf0cab8-9aa2-4148-bb6a-b90d236c8b25.png)

The navigation tabs should retain their default width even in full screen. If need be, the tabs can be left aligned on full screen.

**Comment by beansgum** [comment]
I think it’s normal that the tabs width expands to fill up available space, what we can do is set a maximum width for the window.
