### ISSUE TITLE
Update Dark Mode Icon

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#634]
godcr uses incorrect logo in dark mode

<img width="405" alt="Screen Shot 2021-09-20 at 9 38 39 AM" src="https://user-images.githubusercontent.com/66281245/134040517-dd0afc5d-45da-449a-8446-c11a11f93500.png">

The UI should switch to using 

<img width="128" alt="godcr-master-icon" src="https://user-images.githubusercontent.com/66281245/134040621-5e170bb0-ee31-490d-a2d7-d38e1836fb6a.png"> 

this icon instead

Somewhat related to [this issue](https://github.com/planetdecred/godcr/issues/568)

**Comment by devchoplife** [comment]
Yeah 
It was suspended until after the first release. I will add it to https://github.com/planetdecred/godcr/issues/568 as they all fall under dark mode issues.

**Comment by devchoplife** [comment]
It has been added to #568

**Comment by monsa00** [comment]
This is now a duplicate of 568.
