### ISSUE TITLE
button to show/hide wallet balance

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#639]
we could look at possibility of adding an icon beside the balance(s), to show/hide the wallet balance, this is desirable because it enhances the users privacy

**Comment by dreacot** [comment]
@fegor_clinton please provide a UI for this

**Comment by Sirmorrison** [comment]
This would better be an option from the app settings page or the wallet settings page.

**Comment by dreacot** [comment]
Not really that's not the intended behaviour, the user needs to be able to quickly view and hide the total wallet balance without having to go to the settings page, you'd see similar behaviours in banking apps, it's meant to be an easy to use feature
