### ISSUE TITLE
USD equivalent balance is missing from the top nav

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#641]
The USD equivalent balance is missing from the top nav even when it's enabled in settings.

This was previously implemented here https://github.com/planetdecred/godcr/pull/380

I believe it might have been removed by accident, it should be re-added back if that's the case

<img width="798" alt="Screenshot 2021-09-23 at 7 57 36 AM" src="https://user-images.githubusercontent.com/25265396/134465976-c5e44e97-a8d1-42c8-a034-7e22b3a49ce7.png">

What it should look like

<img width="800" alt="Screenshot 2021-06-30 at 3 36 50 PM" src="https://user-images.githubusercontent.com/25265396/123979877-ff938580-d9b8-11eb-8f0a-0842d12492e6.png">

**Comment by amass01** [comment]
Looks like a good first issue, would like to work on it.

**Comment by dreacot** [comment]
@amass01 it's currently not assigned to anyone, so go ahead, and update the godcr room(https://matrix.to/#/%23godcr:planetdecred.org) you'd be working on it
