### ISSUE TITLE
view property option doesn't do anything when clicked

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#643]
On the wallet's page, the view property option menu doesn't perform any action when clicked

![Screenshot from 2021-09-24 00-05-27](https://user-images.githubusercontent.com/25265396/134595218-4a13d359-3be3-4226-89b3-228271c7a1b4.png)

**Comment by Sirmorrison** [comment]
There is currently no functionality for this or a mock up ui so its currently not a bug.

**Comment by dreacot** [comment]
@fegor_clinton, please provide the necessary UI

**Comment by Fegor-Clinton** [comment]
Okay, I'll get right on it

**Comment by Sirmorrison** [comment]
Feature is not part of the v2 layout.
