### ISSUE TITLE
Replace all instances of "seed phrase", "spending password" and "startup password" with 'seed words', 'spending passphrase', and 'startup passphrase'

### ISSUE THREAD

**Issue by Clariceco** [planetdecred/godcr#647]
Find/Replace ALL instances of: "seed phrase" with 'seed words', 
Find/Replace All:  "spending password" with 'spending passphrase', and 
Find/Replace All: "startup password" with 'startup passphrase' @Sirmorrison @devchoplife

**Comment by Sirmorrison** [comment]
From the conversation i had with @raedah on the pass phrase, we wanted to ensure uniformity across mobile and godcr. 
Currently the mobile use password or pin. We agreed to leave password as it is.
