### ISSUE TITLE
Transactions page update

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#651]
Currently, this is what the transactions page look like.
![image](https://user-images.githubusercontent.com/27733432/135847512-e8fe39bb-aceb-400f-b4d8-5f9c3ef0ef8a.png)

It should be updated to.
![image](https://user-images.githubusercontent.com/27733432/135847430-653a0a80-f32d-4b62-90a8-0637f27ee9b7.png)

And the transactions details hash to this
![image](https://user-images.githubusercontent.com/27733432/135847785-a82e8d19-df68-4fae-a497-bc460fabe880.png)

**Comment by devchoplife** [comment]
Working on this
