### ISSUE TITLE
Uptime bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#653]
On the statistics page, the uptime displayed starts from when he statistics page is opened.
![image](https://user-images.githubusercontent.com/27733432/135864133-bcf08d4a-e5d8-43ec-8cc1-e841539f0bb0.png)

The time to be displayed is the total time the application has been opened and not when the page is opened as exiting the page and opening it again, starts the time from 0.

**Comment by devchoplife** [comment]
Working on this issue
