### ISSUE TITLE
Add concensus voting capability

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#655]
Concensus voting functionality should be added to godcr.
The following documentation should be able to assist.
https://docs.decred.org/governance/consensus-rule-voting/overview/
https://docs.decred.org/governance/consensus-rule-voting/how-to-vote/

**Comment by monsa00** [comment]
If the voting interface is hidden due to wallet not having any tickets, this should be made clear in the UI.

**Comment by monsa00** [comment]
If no proposals have active voting it should be made clear in the interface

**Comment by monsa00** [comment]
temporarily blocked by https://github.com/planetdecred/godcr/pull/769

**Comment by monsa00** [comment]
temporarily blocked by https://github.com/planetdecred/dcrlibwallet/pull/225

**Comment by Sirmorrison** [comment]
#769 and https://github.com/planetdecred/dcrlibwallet/pull/225 are now merged work and progress and usual.
