### ISSUE TITLE
Tab button to switch editor bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#670]
Pressing tab button a couple of times before a page with tab is opened, makes the tabs to jump a couple of editors.

![ezgif com-gif-maker(11)](https://user-images.githubusercontent.com/27733432/137531606-218b7cb8-e1be-4dbc-9971-f487c4d64468.gif)

**Comment by devchoplife** [comment]
Also, tab key press does not switch editors on Restore wallet page. It can be added to this.

**Comment by devchoplife** [comment]
Working on this
