### ISSUE TITLE
proposals: Crash on tab navigation.

### ISSUE THREAD

**Issue by victorgcramos** [planetdecred/godcr#683]
App crashes when navigating from **Approved** -> **In Discussion**

![godcr-proposals](https://user-images.githubusercontent.com/22639213/140596654-dae18d5c-d715-4908-b917-ed380b22a337.gif)

**Comment by Sirmorrison** [comment]
The proposals section will be undergoing major UI updates.   Any bugs will be resolved with the update

**Comment by victorgcramos** [comment]
@Sirmorrison oh, sure! Thanks 😊

**Comment by devchoplife** [comment]
I cannot reproduce it though, did you build the current master @victorgcramos ?

**Comment by victorgcramos** [comment]
@devchoplife yes, I'm running master. Maybe my wallet syncing status had something to do with it.

**Comment by victorgcramos** [comment]
Thank you guys! 🦬🦬
