### ISSUE TITLE
dropdown bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#688]
When a dropdown menu is opened, and other is clicked, the first dropdown that was opened should be closed. 
2 dropdown menus should not be opened at the same time.

<img width="798" alt="image" src="https://user-images.githubusercontent.com/27733432/140879510-84787f15-cfee-41b9-bb0b-9ae48c02427d.png">

**Comment by devchoplife** [comment]
Working on this issue
