### ISSUE TITLE
dropdown selected account bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#689]
When a wallet is selected from the dropdown menu, and a transaction is selected to view the tx details, returning to the main transaction page, the wallet selection is reverted back to the default.

What is expected that is that the wallet dropdown should retain the initially selected wallet before the transaction was selected to view the details.

![ezgif com-gif-maker(13)](https://user-images.githubusercontent.com/27733432/140880295-ca291f24-71a7-411e-bf09-3b1f7bad885b.gif)

**Comment by devchoplife** [comment]
This affects tickets list page as well
