### ISSUE TITLE
dropdown should use the max width of it's longest content

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#697]
As seen on the status dropdown, the text is truncated to "Under Rev...", the text should display the full content which is under "Under Review"
![Screenshot from 2021-11-22 16-31-51](https://user-images.githubusercontent.com/25265396/142889233-7458bb4a-7474-4d6e-82ec-78941e1b3fcf.png)

**Comment by Sirmorrison** [comment]
This is not ideal reason why the modals where given a max width.
In a situation where the content of the modal is overly long `Under review`, the modal tend to occupy most of the screen and pushing all other contents to on the page to the right.

<img width="612" alt="image" src="https://user-images.githubusercontent.com/27733432/142898520-7fed8760-a9ef-47bb-84b8-2ebb5d92226e.png">

There is currently no restriction on the maximum number of letters that can be used on on modal.

**Comment by dreacot** [comment]
> This is not ideal reason why the modals where given a max width. In a situation where the content of the modal is overly long `Under review`, the modal tend to occupy most of the screen and pushing all other contents to on the page to the right.
> 
> <img alt="image" width="612" src="https://user-images.githubusercontent.com/27733432/142898520-7fed8760-a9ef-47bb-84b8-2ebb5d92226e.png">
> 
> There is currently no restriction on the maximum number of letters that can be used on on modal.

while it seems reasonable to want to shorten a long wallet name, as a wallet name can almost be indefinitely long the "Under Review" has a constant character length, and it's also important information, it should not be shortened
