### ISSUE TITLE
the modal for casting a proposal vote isn't displaying correctly

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#698]
This is what it should look like
![image](https://user-images.githubusercontent.com/25265396/142889919-b61b6352-b776-43e5-bc9d-2ed6713e8e11.png)

This is what it looks like
![Screenshot from 2021-11-22 16-34-37](https://user-images.githubusercontent.com/25265396/142889716-f8f13087-fee2-4f3d-aa50-52019fc5bf6b.png)

**Comment by Sirmorrison** [comment]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/27733432/142895575-a5fe683e-845d-4dc9-ac63-c2a16dd8e3b7.png">
This is also the view from my end.

**Comment by AdimekweEbuka** [comment]
This currently what I'm seeing when built from master

<img width="358" alt="real test two" src="https://user-images.githubusercontent.com/76660305/142902742-df16e4b1-8957-4e69-82a7-47e6d25b9454.png">
