### ISSUE TITLE
the modal for staking a ticket isn't displaying correctly

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#699]
The ''+" button on the modal seems to be shrinked

This is what it should look like

*This is not reproduceable on MacOS and Windows OS hence it seems like an OS related BUG.

![Screenshot from 2021-11-22 16-39-45](https://user-images.githubusercontent.com/25265396/142890635-bed054fc-1326-4d66-a976-b5af4d1f161a.png)

This is what it looks like
![Screenshot from 2021-11-22 16-38-10](https://user-images.githubusercontent.com/25265396/142890489-b8c73abf-f3f9-40f8-bc6a-d7ea40016537.png)

**Comment by Sirmorrison** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/27733432/142894843-f9873bc1-f5b1-466b-a949-b7ffa43f1f0b.png">

this is what it looks like on my end seems to be an OS issue.

**Comment by AdimekweEbuka** [comment]
This is currently how it looks
<img width="329" alt="real test one" src="https://user-images.githubusercontent.com/76660305/142902817-a0eafd24-70d6-4629-b879-094a104090c3.png">

**Comment by devchoplife** [comment]
This is what I have on Ubuntu 
![Screenshot from 2021-11-22 20-09-03](https://user-images.githubusercontent.com/66803475/142920897-45f81db3-c445-4b03-a1b2-72ae6b953d4c.png)

@dreacot what OS did you notice this on?

**Comment by dreacot** [comment]
> This is what I have on Ubuntu ![Screenshot from 2021-11-22 20-09-03](https://user-images.githubusercontent.com/66803475/142920897-45f81db3-c445-4b03-a1b2-72ae6b953d4c.png)
> 
> @dreacot what OS did you notice this on?

Elementary os, based on Ubuntu

**Comment by devchoplife** [comment]
Working on this issue
