### ISSUE TITLE
a rebroadcast button should be added for transactions that were created, but not published

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#700]
Sometimes transactions are created, but not published to the network, a rebroadcast button should be added to the transaction details page of such transactions which calls the `wallet.PublishUnminedTransactions()` function

![Screenshot from 2021-11-22 17-16-59](https://user-images.githubusercontent.com/25265396/142904428-8bb84ce4-8bd3-46ba-acfb-ef301a2bfecd.png)

A screenshot from a similar implementation on dcrandroid
<img src="https://user-images.githubusercontent.com/25265396/142906300-a8e6ea6f-3e1f-48a4-b3c5-55b9d623f289.png" width="300"/>

from discussions with @itswisdomagain,
I quote "I believe I've seen a similar issue. In my case, the tx was never actually broadcasted because of low fee, so it doesn't exist on the blockchain. The rescan will identify the outputs that were spent in that tx as unspent since there's no tx on the blockchain that spends those outputs. A rebroadcast button is a good attempt at fixing it but there's no guarantee the tx will eventually be accepted. I've actually seen the issue a couple times and the ideal fix I believe will be preventing low fees when creating txs on dcrlibwallet."

**Comment by devchoplife** [comment]
Working on this
