### ISSUE TITLE
Enable Mainnet Support

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#708]
Once the initial 1.0 testing is completed, as a final step enable mainnet by default.

**Comment by monsa00** [comment]
Allow to enable testnet by using a command line option such as "--testnet". The app should launch in mainnet by default going forward.

**Comment by monsa00** [comment]
No UI control over network, only via the --testnet cli option.

**Comment by Sirmorrison** [comment]
> Allow to enable testnet by using a command line option such as "--testnet". The app should launch in mainnet by default going forward.

is there a reason for this? Having godcr launch in mainnet by default could be very expensive.
