### ISSUE TITLE
Bug on Stakeshuffle/Mixer page 

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#709]
On StakeShuffle page, when "Danger zone" is clicked twice the contaiiner falls as shown in the video below:

https://streamable.com/9cbyt5

To reproduce:
=======================

- Click on "Danger zone" on stakeshuffle page  
- Click "Danger zone" again

**Comment by Sirmorrison** [comment]
Doing some quick investigation into the behavior, it seems the bug is coming from this line.
https://github.com/planetdecred/godcr/blob/01988a89c4ed254cd1403a64e0f8fcd95443881d/ui/page/wallets/privacy_page.go#L315
