### ISSUE TITLE
Disable disconnect button/update status during disconnection

### ISSUE THREAD

**Issue by crux25** [planetdecred/godcr#724]
Sometimes it takes few seconds for godcr to disconnect from the network. Without any visual update that godcr is disconnecting from the network and with the disconnect button remaining active. If the user isn't looking at the log, the user is likely to click disconnect again with the assumption that the software did not register the previous click. The button is active so each click sends a new command to dcrlibwallet. Fast successive clicks will create a condition where:

- dcrlibwallet receives multiple disconnect command, but disconnects successfully.
- It disconnects and immediately reconnect to the network, because between clicks disconnect button state changed but the user did not realize that.  Possibly related to  #385 

In the video below, I clicked the disconnect button multiple times to reproduce the condition described above. Observe the command window underneath godcr and see the clicks register on the log. Also observe godcr disconnect button state.

https://user-images.githubusercontent.com/4796738/146572487-37a580b1-1ef8-4faf-80df-18fdfe69885f.mp4

**Comment by Sirmorrison** [comment]
fix #385
