### ISSUE TITLE
Enable editor switch using tab on dex modals 

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#730]
Tab key should switch editors on Dex modals

**Comment by monsa00** [comment]
Additionally, the "enter" key on the passwords entry does not work, it adds a newline as a character to the password input field.

<img width="379" alt="Screen Shot 2022-02-09 at 1 52 51 PM" src="https://user-images.githubusercontent.com/66281245/153296569-1b880b77-f1e1-4348-ad7a-efbd2ad54199.png">
