### ISSUE TITLE
Send page Max amount button bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#732]
currently, on the send page, when the Max amount button is clicked, the editor is supposed to be populated with the maximum wallet amount. However, when the button is clicked, nothing happens until you switch to my address and back.

Also, If the amount is highlighted and cleared, the max amount button is not reset.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/27733432/147571848-be5d2dbd-48b6-4030-92cd-ce892877b8f2.gif)

**Comment by devchoplife** [comment]
Working on this
