### ISSUE TITLE
can't input password on send page confirmation modal

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#739]
while trying to send funds to my other account, i'm unable to input my password into the confirmation modal, the input editor keeps going out of focus

<img width="800" alt="Screenshot 2021-12-30 at 1 53 33 PM" src="https://user-images.githubusercontent.com/25265396/147753701-19809b95-c8d1-4437-9911-b29c8ef1e842.png">

**Comment by Sirmorrison** [comment]
Fix #746

**Comment by dreacot** [comment]
not sure why this issue is closed, there's no linked PR
