### ISSUE TITLE
amount input field on the send page doesn't re-validate after changing the sending account

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#743]
I tried sending funds from a wallet with insufficient balance, and i got the error below.
Also note that the next button is active even though the validation failed, that shouldn't be.
![Screenshot from 2021-12-31 14-00-27](https://user-images.githubusercontent.com/25265396/147824738-2c813778-0491-4b97-bf6d-bf99b4e8392b.png)

I then switched to a sending account with sufficient balance and was still getting the insufficient amount error, this is because the validation was not redone when a new sending account was selected
![Screenshot from 2021-12-31 13-58-41](https://user-images.githubusercontent.com/25265396/147824717-8c38b711-fb10-43c2-af29-d202fa0da344.png)

I had to clear the amount input field and re input the amount for the error to disappear

**Comment by devchoplife** [comment]
Working on this
