### ISSUE TITLE
Notifications on macOS open "Script Editor" instead of GoDCR.

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#745]
When GoDCR generates a notification on macOS, the notification comes in as Apple Script, causing Script Editor to launch if you click on the notifcation. Ideally clicking on the notification would raise the GoDCR app into focus on the OS.

<img width="375" alt="Screen Shot 2022-01-01 at 12 31 17 PM" src="https://user-images.githubusercontent.com/66281245/147859669-3359aa44-81cc-4d1c-b5c6-d7684988deed.png">
<img width="396" alt="Screen Shot 2022-01-01 at 12 31 33 PM" src="https://user-images.githubusercontent.com/66281245/147859670-0d224e95-d2a2-4451-8cae-e0c9a18fcad5.png">

**Comment by Sirmorrison** [comment]
This is a know issue from the beeep library on MacOS and we were not able to find a different library as they all depend on thesame frame work.

Collinss was to rewrite the code some time back.
