### ISSUE TITLE
Restructure how key events are handled

### ISSUE THREAD

**Issue by crux25** [planetdecred/godcr#746]
Currently pages/modals subscribe to key events by setting EnableKeyEvent to true, and the events are delivered through KeyEvents channel. This logic works well when only one of the active widgets subscribes for key events. 
If the number of active widgets that subscribe to key events is > 1 -- example modal over a page -- bug arises where Key events for the modal are delivered to the page, because they sharing same channel. Setting EnableKeyEvent to false on the page before modal is displayed doesn't resolve this bug because to receive keyevents the modal sets EnableKeyEvent back to true which enables it for both widgets.

**Comment by Sirmorrison** [comment]
The PR to resolve #739 will also resolve this.

**Comment by dreacot** [comment]
not sure why this issue is closed, there's no linked PR

**Comment by Sirmorrison** [comment]
@crux25 mentioned #739 resolves both since they are linked.

**Comment by crux25** [comment]
You should have closed #739 instead of this. This is a fix for #739  and also a fix for other bugs.
