### ISSUE TITLE
UI freezes when mixer is complete 

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#755]
I launched GoDcr three times and noticed the following:

- The first instance froze the app after logging that the mixer was successful 
- The second instance also froze the app after logging that mixer was successful.
- The third instance did not crash and I left it way longer than the first two, at least twice a long. When I restarted GoDCR the fourth time, I noticed that the funds did not get mixed .

**Comment by Sirmorrison** [comment]
This was reproduced.
++ I think the solution will be add the mixer notification listener to the overview page.
