### ISSUE TITLE
having a wallet with lots of transactions lags the UI

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#757]
I have a wallet with about 1300+ transactions, on the transactions page, selecting the said wallet from the dropdown immediately lags the UI significantly. looking at the scrollbar from the screenshot below, you can have an idea of how far the scroll is

While this particular case might be unlikely for most users to face, it begs to question that we might not be fetching transactions efficiently.

A solution to this would be to paginate the transactions, maybe about 20 transactions returned per page

<img width="795" alt="Screenshot 2022-01-10 at 12 27 45 AM" src="https://user-images.githubusercontent.com/25265396/148705547-d4e8c811-7885-4dee-bbae-d59f813d02de.png">

**Comment by Sirmorrison** [comment]
Yeah thank for this.. what we can do is to implement pagination, such that when the page is scrolled to the bottom, we load a particular number of transactions, and clear same amount of transactions. that way, the app only gets to display a number of transactions at a particular time.
