### ISSUE TITLE
Copy button for receive address is not working

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#762]
The "copy" button next to the receiving address on the receive page does not work. Similarly blue highlighted addresses in the transaction ledger details do not work even though the UI states "Copied" on a pop-up.

<img width="592" alt="Screen Shot 2022-01-17 at 9 16 16 AM" src="https://user-images.githubusercontent.com/66281245/149776038-9010f05e-a955-46af-93ed-ad246a8f3955.png">

**Comment by monsa00** [comment]
Confirmed that this is also not working on FreeBSD amd64.

**Comment by Sirmorrison** [comment]
This is not working for windows as well.
