### ISSUE TITLE
Window stuck if you remove a wallet during sync.

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#765]
If a secondary wallet is removed during sync, the window will become frozen.

``` 2022-01-20 12:35:00.950 [INF] DLWL: Canceling sync. May take a while for sync to fully cancel. ```

May be related to https://github.com/planetdecred/godcr/pull/255

<img width="384" alt="Screen Shot 2022-01-20 at 12 48 33 PM" src="https://user-images.githubusercontent.com/66281245/150419860-e3797dab-de71-46ab-b719-dbec43769416.png">

**Comment by itswisdomagain** [comment]
Maybe related https://github.com/planetdecred/godcr/issues/680.

**Comment by dreacot** [comment]
Seems related to this also https://github.com/planetdecred/godcr/issues/728

**Comment by crux25** [comment]
> Seems related to this also #728

Yes it is related to #728. I've seen this bug while fixing #728.
