### ISSUE TITLE
Set gap limit higher on rescan

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#768]
Wallets restored will often miss additional addresses due to default gap limit being too low. 

-Set gap limit to 1000 on settings -> rescan  to fix decrediton privacy wallets with extended gap limits, only for the advanced settings rescan.

**Comment by dreacot** [comment]
![Screenshot from 2022-06-09 23-56-46](https://user-images.githubusercontent.com/25265396/172958722-1008c1f8-1b79-4818-8dbc-b7cb10f343a6.png)
