### ISSUE TITLE
Refine Agenda UI to match Figma mock-up

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#776]
Refine Agenda UI to match Figma mock-up per @dreacot

**Comment by Sirmorrison** [comment]
Do we have the link to the agenda mock up? if yes, it will be helpful to add it here.

**Comment by dreacot** [comment]
https://www.figma.com/file/e0cYaAzkXyXXPY00v23cQY/GoDCR?node-id=851%3A50840
