### ISSUE TITLE
Allow re-map of mixed/unmixed account in privacy setup for restored wallets

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#780]
If a wallet has had mixing operations on it prior to being imported in GoDCR, mixed/unmixed from the previous wallet app will have imported as account-1 and account-2 (or something else). Allow the user to re-map these when GoDCR enables privacy on restored wallets.

Show a warning regarding mapping incorrectly: "Mapping mixed/unmixed incorrectly can result in potential loss of privacy!" 

Show a dropdown menu for each mixed and unmixed with all the found accounts in the wallets. Do not allow the user to pick the same account for both mixed and unmixed.

<img width="912" alt="Screen Shot 2022-02-02 at 8 45 15 AM" src="https://user-images.githubusercontent.com/66281245/152198365-31bf5eb8-7cb5-40ad-ad95-c42efc21ba76.png">

**Comment by Sirmorrison** [comment]
So looking at the issue statement, the selected wallets come with 2 accounts (Account-1 and account-2) why have a dropdown when we can simply notify the users that we have spotted these 2 account, and if they will like to use it to set up the privacy or will they like set it up automatically.

Although i tried to test this not after import, my mixer accounts were not imported.
