### ISSUE TITLE
View associated tickets button does not open any ticket 

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#792]
On the transaction details page:  if the transaction is a `Vote` or `Revocation` transaction, the `View associated ticket` button is shown. However, when the button is clicked, it does not open the ticket associated with the transaction.

See the video below for more details:
https://streamable.com/6zx9ue

**Comment by dreacot** [comment]
A transaction can't be vote or revoked without having a ticket associated with it, what needs to be done is to redirect to the ticket when the view associated button is clicked
