### ISSUE TITLE
App crashes on wallet deletion

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#793]
When I attempt to remove a wallet from my device, GoDCR crashes with the error log below returned in the terminal:
This issue has been reproduced on Ubuntu, Fedora and Windows.

`goroutine 10 [running]:
decred.org/dcrwallet/v2/wallet.(*Wallet).AccountBalance(0xc000453408, {0x1bd83b8, 0xc0083e6140}, 0x18e2dd80, 0xc0)
	/home/devchoplife/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.0-rc3/wallet/wallet.go:1907 +0xc9
github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountBalance(0xc00025a3c0, 0x1bd83b8)
	/home/devchoplife/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220203081357-951ce632e9d2/accounts.go:108 +0xe6
github.com/planetdecred/dcrlibwallet.(*Wallet).GetAccountsRaw(0xc00025a3c0)
	/home/devchoplife/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220203081357-951ce632e9d2/accounts.go:41 +0x1b4
github.com/planetdecred/godcr/ui/page.(*MainPage).CalculateTotalWalletsBalance(0xc0000c8540)
	/home/devchoplife/GitRepos/godcr/ui/page/main_page.go:257 +0x7b
github.com/planetdecred/godcr/ui/page.(*MainPage).UpdateBalance(0xc000188a80, 0x20)
	/home/devchoplife/GitRepos/godcr/ui/page/main_page.go:235 +0xd5
github.com/planetdecred/godcr/ui/page.(*MainPage).Layout(0xc000188a80, {{{0x0, 0x0}, {0x3ff, 0x344}}, {0x3f800000, 0x3f800000}, {0x1bae680, 0xc00003e518}, {0xc07d98dca681f1fa, ...}, ...})
	/home/devchoplife/GitRepos/godcr/ui/page/main_page.go:500 +0x38
gioui.org/layout.Stack.Layout({0x30}, {{{0x3ff, 0x344}, {0x3ff, 0x344}}, {0x3f800000, 0x3f800000}, {0x1bae680, 0xc00003e518}, {0xc07d98dca681f1fa, ...}, ...}, ...)
	/home/devchoplife/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/stack.go:60 +0x895
github.com/planetdecred/godcr/ui.(*Window).drawWindowUI(0xc0003c5cc0, {{{0x3ff, 0x344}, {0x3ff, 0x344}}, {0x3f800000, 0x3f800000}, {0x1bae680, 0xc00003e518}, {0xc07d98dca681f1fa, ...}, ...})
	/home/devchoplife/GitRepos/godcr/ui/window.go:254 +0x3d9
github.com/planetdecred/godcr/ui.(*Window).displayWindow(0xc0003c5cc0, {{0xc07d98dca681f1fa, 0xb9fcf4773a, 0x2825bc0}, {0x3f800000, 0x3f800000}, {0x3ff, 0x344}, {{0x0, 0x0}, ...}, ...})
	/home/devchoplife/GitRepos/godcr/ui/window.go:217 +0x16c
github.com/planetdecred/godcr/ui.(*Window).HandleEvents(0xc0003c5cc0)
	/home/devchoplife/GitRepos/godcr/ui/window.go:180 +0x10c
main.main.func2()
	/home/devchoplife/GitRepos/godcr/main.go:80 +0x26
created by main.main
	/home/devchoplife/GitRepos/godcr/main.go:79 +0x4d8`

Below is the link to a video that shows how to reproduce the bug:
https://streamable.com/srzm0u

**Comment by Sirmorrison** [comment]
I am unable to reproduce this behavior from my end.
![ezgif com-gif-maker(2)](https://user-images.githubusercontent.com/27733432/155942793-c80c8dbd-f7f0-4dc0-a543-b338f161439e.gif)

Kindly confirm your current master branch is up to date the upstream master.
`git fetch <remote-upstream>`
`git rebase <remote-upstream>/master`
