### ISSUE TITLE
after syncing recent transactions isn't populated

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#795]
For a fresh installation of GoDCR (no previous wallets), restore a wallet that already has transactions, while on the overview page, after sync completes, the recent transactions list doesn't get populated, until after leaving the overview page and returning to it

**Comment by AdimekweEbuka** [comment]
Good morning, Please can you give more clarification or steps on how to replicate this issue, I haven't been able to replicate it. From my observation recent transactions are already visible on the overview page even before sync begins.

**Comment by dreacot** [comment]
@AdimekweEbuka i've updated the description

**Comment by Sirmorrison** [comment]
This still persist.. send funds to an account while on the overview page, they dont show up until the page is left and revisited.
