### ISSUE TITLE
show mixer card for the wallet currently mixing

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#796]
on the wallets page, a mixer card should be shown for the wallet with mixing in progress

![Screenshot from 2022-02-28 12-07-35](https://user-images.githubusercontent.com/25265396/155972998-3c362385-df02-49d2-a337-7a9daee2eb44.png)

![Screenshot_1646047035](https://user-images.githubusercontent.com/25265396/155974450-97e46883-ff12-4901-9347-135476f1ad52.png)

**Comment by Sirmorrison** [comment]
Issue resolved by #812
