### ISSUE TITLE
the vsp input box on the staking modal should be validated

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#797]
Currently the input box accepts spaces as valid input, the input box should be validated to make sure it contains a text before enabling the save button

![Screenshot from 2022-02-28 12-20-17](https://user-images.githubusercontent.com/25265396/155974907-6f6f6a4d-f659-40ce-a89c-668a8ecbaa17.png)

**Comment by AdimekweEbuka** [comment]
Building from master, I was unable to replicate this issue. See attached video below. I am running on a windows 10 OS
![godcr (testnet) 2022-03-18 10-10-41](https://user-images.githubusercontent.com/76660305/158975107-f016147f-a2d8-4994-b0b8-49d93fd6898f.gif)
