### ISSUE TITLE
godcr crashes after running for several hours

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#827]
I left my godcr running on my machine for about 3 hours, came back to see the app had crash.

I wasn't performing any specific action or task, but the last operation done on my wallet was to buy 2 tickets, before stepping out. there's no clear reproducible steps to this issue.

This is the third time I've come across this crash, with pretty much the same crash logs. previous times godcr was left running for about 10 hours, so the timing is not constant as well.

**See log below:**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8754b3]

goroutine 7329 [running]:
decred.org/dcrwallet/v2/wallet/udb.(*Store).ExtendMainChain(0xc000216078, 0x1eeb600, 0xc00058f4c0, 0xc0051f4dd0, 0x0, 0xc00058f4c0, 0xc0030bf690)
        /home/kennedy/Projects/pkg/mod/decred.org/dcrwallet/v2@v2.0.1/wallet/udb/txmined.go:273 +0x6f3
decred.org/dcrwallet/v2/wallet.(*Wallet).extendMainChain(0xc00000cd20, 0x1ed8c38, 0xc003cf4200, 0x19319d6, 0x12, 0x1ee19d0, 0xc0005a52c0, 0xc0051f4dd0, 0x0, 0x0, ...)
        /home/kennedy/Projects/pkg/mod/decred.org/dcrwallet/v2@v2.0.1/wallet/chainntfns.go:37 +0x11a
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch.func1(0x1ee19d0, 0xc0005a52c0, 0x1929f86, 0xe)
        /home/kennedy/Projects/pkg/mod/decred.org/dcrwallet/v2@v2.0.1/wallet/chainntfns.go:160 +0x499
decred.org/dcrwallet/v2/wallet/walletdb.Update(0x1ed8c38, 0xc003cf4200, 0x1ed8f48, 0xc000568800, 0xc0030bfbb0, 0x0, 0x0)
        /home/kennedy/Projects/pkg/mod/decred.org/dcrwallet/v2@v2.0.1/wallet/walletdb/interface.go:249 +0x1b1
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch(0xc00000cd20, 0x1ed8c38, 0xc003cf4200, 0xc0000f7a70, 0xc0005a4a80, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /home/kennedy/Projects/pkg/mod/decred.org/dcrwallet/v2@v2.0.1/wallet/chainntfns.go:104 +0x277
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).getHeaders(0xc0000f79e0, 0x1ed8c38, 0xc00362d280, 0xc0032381c0, 0x1, 0x1)
        /home/kennedy/Projects/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/spv/sync.go:1381 +0x785
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).startupSync(0xc0000f79e0, 0x1ed8c38, 0xc00362d280, 0xc0032381c0, 0x1d23158, 0x0)
        /home/kennedy/Projects/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/spv/sync.go:1451 +0x1d0
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1.2(0xc0000f79e0, 0x1ed8c38, 0xc00362d280, 0xc0032381c0, 0xc0005a6cc0)
        /home/kennedy/Projects/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/spv/sync.go:576 +0x4d
created by github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1
        /home/kennedy/Projects/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.6.2-0.20220315164532-e871b673497a/spv/sync.go:575 +0x5e5
```

Version: Testnet 2022-02-24
Machine: elementary OS 5.1.7 Hera (Built on Ubuntu 18.04.6 LTS)

**Comment by dreacot** [comment]
@itswisdomagain what are your thoughts on this

**Comment by itswisdomagain** [comment]
I'm investigating this, looks like a minor issue with the spv syncer's `getHeaders` method. I have a tentative fix here: https://github.com/itswisdomagain/dcrlibwallet/commit/fa7dbededec7f280ddfeae69c223fa62a52265de. Testing that commit from godcr to be sure nothing gets broken before I send a PR in.

**Comment by itswisdomagain** [comment]
@dreacot Can you please test godcr with this dcrlibwallet replace to see if this issue is resolved?
`replace github.com/planetdecred/dcrlibwallet => github.com/itswisdomagain/dcrlibwallet v1.0.0-rc1.0.20220404125820-edfb862bcc9a`

**Comment by dreacot** [comment]
will do

**Comment by raedah** [comment]
2022-06-16 03:46:46.165 [WRN] DLWL: Failed to handle headers announced by 89.212.19.49:9108: spv.handleBlockAnnouncements(89.212.19.49:9108): I/O error:: remotepeer(89.212.19.49:9108).CFilterV2(000000000000000006507c1af936c17d43e7e6dfa79c5b750ed9847f52a1c424): peer appears stalled
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x821b59]

goroutine 300862 [running]:
decred.org/dcrwallet/v2/wallet/udb.(*Store).ExtendMainChain(0xed9847f52a1c424?, {0x1dfd358?, 0xc0052e0400}, 0xc00277c270, 0x0)
/home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/udb/txmined.go:273 +0x679
decred.org/dcrwallet/v2/wallet.(*Wallet).extendMainChain(0xc002c705a0, {0x1df5278, 0xc0036d7c80}, {0x18160c4, 0x12}, {0x1df81c8, 0xc00052e358}, 0x19?, 0x0?, {0x0, ...})
/home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:37 +0x113
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch.func1({0x1df81c8, 0xc00052e358})
/home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:160 +0x890
decred.org/dcrwallet/v2/wallet/walletdb.Update({0x1df5278, 0xc0036d7c80}, {0x1df5588, 0xc00289e240}, 0xc0005cfbf0)
/home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/walletdb/interface.go:249 +0x195
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch(0xc002c705a0, {0x1df5278, 0xc0036d7c80}, 0xc0025822e8, {0xc00052e148, 0x1, 0x1}, 0x0)
/home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:104 +0x2da
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).getHeaders(0xc0025b4500, {0x1df5278, 0xc0036d6080}, 0xc00416ca80)
/home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:1384 +0xaaa
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).startupSync(0xc0025b4500, {0x1df5278, 0xc0036d6080}, 0xc00416ca80)
/home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:1454 +0x170
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1.2()
/home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:579 +0x37
created by github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1
/home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:578 +0x578
