### ISSUE TITLE
Wallet restore seed validation bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#828]
On the Wallet page, when you try import a new wallet, an `invalid seed phrase` error is displayed just when you start typing the last seed.

Allow validation to start only after the last seed phrase has been entered.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/27733432/160187232-563b7917-d267-4223-a58e-cc483c95c12f.png">

**Comment by raedah** [comment]
Also note that clicking on an different entry field shows an invalid word completion suggestion that correspond with the last field actually input into. Suggestions should likely not be shown if a completed word is already input and matches.

**Comment by monsa00** [comment]
Tab completion should default to the first word in the list instead of leaving the half-typed word as well.
