### ISSUE TITLE
Send page formatting in dark mode and text update

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#831]
Update Send page to say "Destination Address" instead of just "Address".  

Additionally, the page rendering is not correct in dark mode for the send page:

<img width="848" alt="Screen Shot 2022-03-25 at 2 35 49 PM" src="https://user-images.githubusercontent.com/66281245/160205115-7f7edfb9-7591-4a7f-ab80-9a20aefd05eb.png">

**Comment by dreacot** [comment]
![Screenshot from 2022-03-31 14-18-45](https://user-images.githubusercontent.com/25265396/161064067-1e9fc7b9-6ecd-415b-b855-e3c293aa226b.png)

Switching from light to dark mode and then light mode back;
1. the max button is still in dark mode
2. the next button is still in dark mode
3. typing a text in the amount input field doesn't show the amount being inputted(it's white)
