### ISSUE TITLE
Skip "Set up needed accounts" option screen for privacy if no additional accounts detected in wallet

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#853]
Privacy setup currently allows the user to manually setup accounts even if the wallet has no additional accounts to map. This should be auto detected (the lack of accounts) and can infer the user has to setup new accounts if none exist.

![godcr-issue](https://user-images.githubusercontent.com/66281245/160873739-3a3e2a9b-e16a-456b-9efc-b9116f4d809e.jpg)

**Comment by dreacot** [comment]
Just a heads up. 
There's a hidden account created for every wallet called "imported", So checking if the wallet has just one account, wouldn't work as intended.

We could check if a wallet has more that one account and also check to ignore counting accounts with the name "imported" before hiding that page
