### ISSUE TITLE
Amount editor does not revalidate after switching source/destination accounts 

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#861]
On semd page, the amount editor does not revalidate when source or destination account is switched.
![send bug](https://user-images.githubusercontent.com/66803475/161020833-592217a8-09f5-4468-8cf2-c0523209cedc.gif)

**Comment by Sirmorrison** [comment]
Issue not reproducible as it seemed to have been resolved as part of https://github.com/planetdecred/godcr/pull/879
