### ISSUE TITLE
Floating action button on the wallets page, obscures texts and buttons for the last item on the list

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#866]
While on the wallets page, there's a FAB at the bottom right of the screen, which sometimes obscures text or button for the last item in the scroll able list.

**Screenshots**
![Screenshot from 2022-03-31 17-14-52](https://user-images.githubusercontent.com/25265396/161153297-27d3ab00-a51f-4e50-be9d-e038ed81c7e4.png)
![Screenshot from 2022-03-31 17-12-00](https://user-images.githubusercontent.com/25265396/161153298-0a2ee46d-816a-483a-8218-2dee055af92c.png)

Gmail and WhatsApp's solution to this was to add a margin that's the same height as the FAB in place of the last item.

<img src="https://user-images.githubusercontent.com/25265396/161153762-9a932ccc-a463-4eed-b5f7-5332bc558c62.jpg" width="300" />

**Whatsapp**

<img src="https://user-images.githubusercontent.com/25265396/161153917-64079f0c-8bdd-47f5-8ca8-6df30b262d06.jpg" width="300" />

**Gmail**

**Comment by Sirmorrison** [comment]
Mock up design for this 
https://www.figma.com/file/e0cYaAzkXyXXPY00v23cQY/GoDCR-%26-DCRMobile?node-id=2294%3A102017

<img width="839" alt="image" src="https://user-images.githubusercontent.com/27733432/161291304-b3264351-18a8-4076-b77f-cdd9597fadf6.png">
