### ISSUE TITLE
App launches into a frozen state if auto-sync is enabled but the network is offline

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#875]
godcr launches into a frozen state if auto-sync is enabled but the network is offline. Disabling auto-sync allows the app to launch while offline.

**Comment by Sirmorrison** [comment]
![ezgif com-gif-maker(11)](https://user-images.githubusercontent.com/27733432/162573735-17439334-e068-4d7a-b2c9-3be4a63c20dd.gif)

I am currently unable to reproduce this. I have auto sync on and turned off my network. Although i noticed it lags though.

**Comment by monsa00** [comment]
Confirmed, no longer able to reproduce on master. Closing.
