### ISSUE TITLE
Governance UI improvements

### ISSUE THREAD

**Issue by raedah** [planetdecred/godcr#876]
- Selector for oldest/newest is not needed for Proposals or Consensus Changes. Just use newest first order always.
- Status selector (approved, rejected, etc) should also have an All option. Can also show a count like the android mobile wallet does on the selector for the transactions page.
- Remove wallet selector from Consensus Changes page. 
- Add status selector.
- Voting Preference: yes    can instead read   Vote Choice: [wallet1] yes, [wallet2] yes
- Update Preference button can instead say  Set Choice
- Title can change to Set Vote Choice
- ID field and title field are redundant. Get rid of the ID field. Don't capitalize the title. 
- Remove grayed out voting preference button on votes that are no longer active. Also, no need to show Vote Choice here.
- On the voting dashboard popup, also display a link to https://github.com/decred/dcps  for dcps info.
- Latest agenda order should be reversed for consistency with the rest of the older agendas.
- Search boxes dont work.
- Reload button is not needed on the Consensus Changes page.

**Comment by Sirmorrison** [comment]
https://www.figma.com/file/e0cYaAzkXyXXPY00v23cQY/GoDCR-%26-DCRMobile?node-id=1239%3A63393 associating designs.
