### ISSUE TITLE
Crash when fetching agendas on mainnet

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#883]
Segfault when fetching mainnet agendas. [Logs](https://bpa.st/3IPQ)

**Comment by dreacot** [comment]
@monsa00 the linked log won't last forever, would probably not be visible after a week, it's best to add the log to the issue description, so future references can easily be made

**Comment by monsa00** [comment]
[crash.log.txt](https://github.com/planetdecred/godcr/files/8485546/crash.log.txt)
