### ISSUE TITLE
Automatic Ticket Buyer stopping prematurely

### ISSUE THREAD

**Issue by monsa00** [planetdecred/godcr#889]
Automatic ticket buyer periodically stops before the minimum balance has been met. It does not occur every time, but I suspect the ticket buyer is turning off before the change comes back from ticket purchases.

**Comment by monsa00** [comment]
Ticket buyer was set to maintain 100 minimum balance:

<img width="595" alt="Screen Shot 2022-05-05 at 1 23 21 PM" src="https://user-images.githubusercontent.com/66281245/167019449-967649e1-fd40-4396-ae67-320ab2111475.png">

it could have purchased one more ticket before stopping. 

Note: In order to see that the ticket buyer has turned off, one must leave the staking page and return. The switch will have changed state, but only when you leave the page.

**Comment by monsa00** [comment]
It may not be necessary to stop the auto ticket buyer. Once the process is started, why not just let it run until the user either switches the ticket buyer toggle back off, or the app is quit?

**Comment by Sirmorrison** [comment]
> It may not be necessary to stop the auto ticket buyer. Once the process is started, why not just let it run until the user either switches the ticket buyer toggle back off, or the app is quit?

Currently, the ticker buyer works with context and checks the context.Done(). if it meets this condition, the buying process stops. we can however see how to prevent it from shutting down when the funds are exhausted.
