### ISSUE TITLE
ios and android ?

### ISSUE THREAD

**Issue by gedw99** [planetdecred/godcr#894]
I gave it a shot anyway to see ....

IOS:

```  
gogio -o godcr.app -target ios .
xcrun simctl install booted godcr.app 
``` 

![Screenshot 2022-04-22 at 12 19 43](https://user-images.githubusercontent.com/53147028/164689478-1b04b704-cd55-4e96-9b46-f246f93ee00b.png)

ANDROID:

```
gogio -target android .
gogio: go build -ldflags=-w -s -X gioui.org/app/internal/log.appID=com.github.godcr -buildmode=c-shared -tags  -o /var/folders/wp/ff6sz9qs6g71jnm12nj2kbyw0000gp/T/gogio-3048283512/jni/x86/libgio.so . failed: # github.com/lib/pq
../../../../pkg/mod/github.com/lib/pq@v1.10.3/user_posix.go:13:6: userCurrent redeclared in this block
	../../../../pkg/mod/github.com/lib/pq@v1.10.3/user_other.go:8:6: other declaration of userCurrent

```

has a postres driver dependency that is messing things up for android ?

**Comment by Sirmorrison** [comment]
looking through the http://github.com/lib/pq, i see this issue was resolved by the PR https://github.com/lib/pq/pull/1060

**Comment by Sirmorrison** [comment]
gogio has a new update https://pkg.go.dev/gioui.org/cmd@v0.0.0-20220508120214-35e56c5af956/gogio as well.

**Comment by Sirmorrison** [comment]
After further review, it was found out that godcr is references an older version of pq library

![image](https://user-images.githubusercontent.com/27733432/167798010-130e225a-1db5-4875-9203-48abb268f21a.png)

**Comment by gedw99** [comment]
Any reason why the client gui even as a reference to PostgreSQL driver ? Just curious

**Comment by dreacot** [comment]
@gedw99 yes, a detailed comment was left here https://github.com/planetdecred/godcr/pull/924/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R28

**Comment by gedw99** [comment]
ah makes sense now . thanks
