### ISSUE TITLE
Hide all accounts that are not mixed accounts on the send page.

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#908]
currently, on the send page, if the only wallet account in the wallet is the default account, the show up in the list of accounts to send from instead of hide the wallet completely.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/27733432/166196052-dd293231-951c-4e2f-b5a4-5e9846565856.png">

Until the `Allow spending from unmixed account` option is turned on, the only accounts to be displayed is the mixed accounts.

**Comment by dreacot** [comment]
Is privacy enabled for the def wallet?

**Comment by Sirmorrison** [comment]
Nope.
