### ISSUE TITLE
Verify message bug

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#912]
after signing a message from the send page, trying to verify same message return false after all checks have passed.

**Comment by Sirmorrison** [comment]
This seems to be an upstream bug.
Local codes is up to date with dcrwallet master for sign message and verify message.

I have tested on decrediton.. generated a signature, and tried verifying it and the invalid signature error pop up.

address: TsYYKeoH94fkyZr4Jkvk9WcQkW8LRjxx9yL
message: test
signature: Hx5i6DXPWeWbSb37PUq57MWNLtx4Js4dztOjepIebZSiaC3Twfx5VDgx1OIGWYVBfIe+iDT056cS4ZWHbl28Z4o=

Decrediton error
<img width="832" alt="image" src="https://user-images.githubusercontent.com/27733432/166873221-ed6db81f-98a1-4b0c-9ce0-6111ca5c12b2.png">

godcr error
<img width="799" alt="image" src="https://user-images.githubusercontent.com/27733432/166873444-a1a245a9-c10a-4231-963a-f1c8264cc36f.png">

**Comment by davecgh** [comment]
Resolved by decred/dcrwallet#2150.
