### ISSUE TITLE
Make Stake Shuffle Page scrollable.

### ISSUE THREAD

**Issue by crux25** [planetdecred/godcr#928]
On the stake shuffle page, if the app window isn't enlarged to fit the size of the entire screen, the options at the bottom of the screen is not accessible. 
See image below.
![stake-shuffle-page](https://user-images.githubusercontent.com/4796738/169009011-79f37f32-7dcf-4c52-95bc-10d941b700be.png)

**Comment by Sirmorrison** [comment]
This Page is currently scrollable.

![ezgif com-gif-maker(17)](https://user-images.githubusercontent.com/27733432/169038307-ff781891-55ed-4bda-9dcd-6afe3d203967.gif)

**Comment by crux25** [comment]
I am closing because scrolling works with trackpad, but doesn't work with up/down arrow keys. I am made to understand that the behavior is consistent with design.
