### ISSUE TITLE
Nevigating to the wallets tab logs random numbers.

### ISSUE THREAD

**Issue by crux25** [planetdecred/godcr#929]
On navigating to the wallets page a random number is logged that pollutes the log space.
To recreate error. Start godcr, navigate to the wallets tab and watch the log. 

![create-wal-num-error](https://user-images.githubusercontent.com/4796738/169029249-cf82d0a9-0bf9-4f7e-95b7-337f0adb701b.png)

**Comment by Sirmorrison** [comment]
Unable to reproduce this.

https://user-images.githubusercontent.com/27733432/169046945-e655973b-c9c1-4c6d-9520-8ae8ee1e5e98.mov

**Comment by crux25** [comment]
@Sirmorrison are you on current master?

**Comment by crux25** [comment]
https://user-images.githubusercontent.com/4796738/169058142-1ebd7678-2db2-4f14-9b12-a2a90dc3b5a1.mp4

You can see I just pulled from master, then build. We need more testers.
