### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by raedah** [planetdecred/godcr#946]
2022-05-23 03:21:20.477 [INF] DLWL: [6] Received sidechain or orphan block 0000000000000000182e82935f56e1e078fe089ccd21f73960b1656e92504d38, height 661410
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x821299]

goroutine 7738336 [running]:
decred.org/dcrwallet/v2/wallet/udb.(*Store).ExtendMainChain(0x60b1656e92504d38?, {0x1c9ea80?, 0xc002e4a2c0}, 0xc00adfa750, 0x0)
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/udb/txmined.go:273 +0x679
decred.org/dcrwallet/v2/wallet.(*Wallet).extendMainChain(0xc000000960, {0x1c96c58, 0xc003d7de00}, {0x16ca631, 0x12}, {0x1c9a408, 0xc00db7af38}, 0x16?, 0x0?, {0x0, ...})
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:37 +0x113
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch.func1({0x1c9a408, 0xc00db7af38})
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:160 +0x890
decred.org/dcrwallet/v2/wallet/walletdb.Update({0x1c96c58, 0xc003d7de00}, {0x1c96f68, 0xc00009c240}, 0xc002d13bf0)
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/walletdb/interface.go:249 +0x195
decred.org/dcrwallet/v2/wallet.(*Wallet).ChainSwitch(0xc000000960, {0x1c96c58, 0xc003d7de00}, 0xc0052f4870, {0xc00db7aa00, 0x1, 0x1}, 0x0)
        /home/user/go/pkg/mod/decred.org/dcrwallet/v2@v2.0.2-0.20220505152146-ece5da349895/wallet/chainntfns.go:104 +0x2da
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).getHeaders(0xc000654a00, {0x1c96c58, 0xc003d7cc00}, 0xc00f120e00)
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:1384 +0xaaa
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).startupSync(0xc000654a00, {0x1c96c58, 0xc003d7cc00}, 0xc00f120e00)
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:1454 +0x170
github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1.2()
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:579 +0x37
created by github.com/planetdecred/dcrlibwallet/spv.(*Syncer).connectToCandidates.func1
        /home/user/go/pkg/mod/github.com/planetdecred/dcrlibwallet@v1.7.0/spv/sync.go:578 +0x578

**Comment by dreacot** [comment]
@itswisdomagain seems we are still getting this error
