### ISSUE TITLE
App crashes when Stake is clicked 

### ISSUE THREAD

**Issue by devchoplife** [planetdecred/godcr#955]
Godcr crashes when the stake button is clicked 

![stake-crash1](https://user-images.githubusercontent.com/66803475/170554156-8dc07d21-16d3-431f-bc73-0f326b38c022.gif)

Error Log
================,
`panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x112df9b]

goroutine 15 [running]:
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).Layout.func2({{{0x0, 0x0}, {0x114, 0xf4204}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/page/components/account_selector.go:180 +0x3b
gioui.org/layout.Flex.Layout({0x38?, 0x1?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x134, 0xf4204}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/flex.go:99 +0xf15
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x134, 0xf4204}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:84 +0x6a
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x134, 0xf4204}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:173 +0x175
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x134, 0x0}, {0x134, 0xf4204}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:83 +0xbd
gioui.org/layout.Inset.Layout({{0x0?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?}}, {{{0x134, 0x0}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:146 +0x3ff
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x14c, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:81 +0xf1
github.com/planetdecred/godcr/ui/decredmaterial.Border.Layout({{0x0?, 0x0?, 0x0?, 0x0?}, {0x0?, 0x0?, 0x0?, 0xfb9494?}, {0x0?, 0xb0?}}, ...)
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/border.go:21 +0x9e
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2({{{0x14c, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:79 +0x1ce
gioui.org/layout.Stack.Layout({0xb0?}, {{{0x0, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/stack.go:60 +0xa55
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:45 +0x256
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:103 +0x203
gioui.org/layout.Inset.Layout({{0x1a2?, 0x0?}, {0x3bf8ab0?, 0xc0?}, {0x136?, 0x0?}, {0x135?, 0x0?}}, {{{0x0, 0x0}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:146 +0x3ff
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:42 +0xf1
gioui.org/layout.Direction.Layout(0x0, {{{0x0, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:173 +0x175
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout({0xfffffffffffffffe, 0xffffffffffffffff, 0x0, {0x0, 0x0, 0x0, 0x0}, 0x0, {{0x3d, 0x3d, ...}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:40 +0x13d
github.com/planetdecred/godcr/ui/page/components.(*AccountSelector).Layout(0xc003f12f00, {{{0x14c, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/page/components/account_selector.go:169 +0x545
gioui.org/layout.Flex.Layout({0x9e?, 0x1?, 0x0?, 0x0?}, {{{0x14c, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/flex.go:99 +0xf15
github.com/planetdecred/godcr/ui/page/staking.(*stakingModal).Layout.func2.1({{{0x14c, 0x0}, {0x14c, 0xf421c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/page/staking/purchase_modal.go:208 +0x345
gioui.org/layout.Inset.Layout({{0x0?, 0x0?}, {0x41200000?, 0x0?}, {0x0?, 0x0?}, {0x3bf8ab0?, 0xc0?}}, {{{0x14c, 0x0}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:146 +0x3ff
github.com/planetdecred/godcr/ui/page/staking.(*stakingModal).Layout.func2({{{0x168, 0x0}, {0x168, 0xf422c}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/page/staking/purchase_modal.go:207 +0xbd
gioui.org/layout.Inset.Layout({{0x1a2?, 0x0?}, {0x3bf8ab0?, 0xc0?}, {0x134?, 0x0?}, {0x133?, 0x0?}}, {{{0x168, 0x0}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:146 +0x3ff
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.2.2({{{0x17c, 0x0}, {0x17c, 0xf4240}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...}, ...)
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/modal.go:130 +0xad
gioui.org/layout.(*List).Layout(0xc00236f800, {{{0x17c, 0x0}, {0x17c, 0xf4240}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/list.go:116 +0x1a2
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1.2({{{0x17c, 0x0}, {0x17c, 0x142}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/modal.go:129 +0x345
gioui.org/layout.Flex.Layout({0x2?, 0x1?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/flex.go:99 +0xf15
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1.1({{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:84 +0x6a
gioui.org/layout.Direction.Layout(0x8, {{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:173 +0x175
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1.1({{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:83 +0xbd
gioui.org/layout.Inset.Layout({{0x44?, 0x0?}, {0x320?, 0x0?}, {0x21f?, 0x0?}, {0x0?, 0x0?}}, {{{0x0, 0x0}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:146 +0x3ff
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2.1({{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:81 +0xf1
github.com/planetdecred/godcr/ui/decredmaterial.Border.Layout({{0xc?, 0x68?, 0x0?, 0x0?}, {0x0?, 0x6803?, 0x0?, 0xfb9494?}, {0x0?, 0xd0?}}, ...)
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/border.go:21 +0x9e
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1.2({{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:79 +0x1ce
gioui.org/layout.Stack.Layout({0xa4?}, {{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/stack.go:60 +0xa55
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1.1({{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:45 +0x256
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1.1({{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:103 +0x203
gioui.org/layout.Inset.Layout({{0x163?, 0x0?}, {0x3bf8ab0?, 0xc0?}, {0x100?, 0x0?}, {0xff?, 0x0?}}, {{{0x0, 0x0}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:146 +0x3ff
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout.func1({{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:42 +0xf1
gioui.org/layout.Direction.Layout(0x8, {{{0x0, 0x0}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:173 +0x175
github.com/planetdecred/godcr/ui/decredmaterial.LinearLayout.Layout({0xffffffffffffffff, 0xffffffffffffffff, 0x1, {0x25, 0x25, 0x25, 0xff}, 0x0, {{0x0, 0x0, ...}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/linearlayout.go:40 +0x13d
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2.1({{{0x0, 0x1f4}, {0x17c, 0x1f4}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/modal.go:93 +0x445
gioui.org/layout.Inset.Layout({{0x0?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?}, {0x0?, 0x0?}}, {{{0x0, 0x1f4}, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/layout.go:146 +0x3ff
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout.func2({{{0x0, 0x258}, {0x17c, 0x258}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/modal.go:81 +0x33c
gioui.org/layout.Stack.Layout({0xb0?}, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/stack.go:60 +0xa55
github.com/planetdecred/godcr/ui/decredmaterial.(*Modal).Layout(0xc000236028, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/decredmaterial/modal.go:58 +0x2f6
github.com/planetdecred/godcr/ui/page/staking.(*stakingModal).Layout(0xc000236000, {{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/page/staking/purchase_modal.go:259 +0x185
github.com/planetdecred/godcr/ui.(*Window).drawWindowUI.func2({{{0x0, 0x0}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, 0x6668f16d5, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/window.go:224 +0xe4
gioui.org/layout.Stack.Layout({0x45?}, {{{0x320, 0x258}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...}, ...)
        C:/Users/M.Durojaiye/go/pkg/mod/gioui.org@v0.0.0-20211011183043-05f0f5c20f45/layout/stack.go:60 +0xa55
github.com/planetdecred/godcr/ui.(*Window).drawWindowUI(0xc00009e2a0, {{{0x320, 0x258}, {0x320, 0x258}}, {0x3f800000, 0x3f800000}, {0x1c22200, 0xc000c40098}, {0xc09c0ff14009b1a4, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/window.go:234 +0x3b9
github.com/planetdecred/godcr/ui.(*Window).displayWindow(0xc00009e2a0, {{0xc09c0ff14009b1a4, 0x6668f16d5, 0x27a2da0}, {0x3f800000, 0x3f800000}, {0x320, 0x258}, {{0x0, 0x0}, ...}, ...})
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/window.go:197 +0x16c
github.com/planetdecred/godcr/ui.(*Window).HandleEvents(0xc00009e2a0)
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/ui/window.go:164 +0x10c
main.main.func2()
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/main.go:80 +0x26
created by main.main
        C:/Users/M.Durojaiye/Documents/GitRepos/godcr/main.go:79 +0x4d3`

**Comment by Sirmorrison** [comment]
I am unable to reproduce this.
