### ISSUE TITLE
UI Improvements for Next Gen

### ISSUE THREAD

**Issue by Joshuaikenna9** [planetdecred/godcr#966]
- [ ] Rework on the staking page making changes to the color used to represent each ticket and the information contained in it.    
    - Unmined should show the amount of time passed in minutes and seconds since it was sent.
    - Immature should show number of blocks remaining till mature.
    - Live should show how many days its been live for and how many days remain till expiry. 
    - Voted should show the time stamp for when it voted, and can also show the time since voted.
    - Expired should show the time stamp it expired on and how many days past when it expired.
    - Missed should show the time stamp and block number.
    - Revoked should show the time stamp. 
    - Change the colors of the staking tickets on the staking page.
    - Change the colors of the staking tickets on their individual staking details page.
    - Add the statistics modal to the staking page.

- [ ] Rework on the wallet selector list by adding the sync indicator, back up indicator, and ability to switch from wallet view to a DEX view and App settings view.
    - Add the backup indicator to each wallet.
    - Add the sync indicator to each wallet.
    - Add the icon of DCR and BTC to each wallet icon.
    
- [ ] Work on market, wallet, notification, profile and settings for the DEX

- [ ] Rework on the create and restore wallet feature adding seed word and HEX.
    - Replace create wallet and restore wallet buttons with an Add wallet.
    -  Add seed word and HEX option while creating a wallet.
    -  Add seed word and HEX option while restoring a wallet.

**Comment by Sirmorrison** [comment]
This task from my POV is too bulky…

I already started work on the V2 layout design. When this is done, we intend to break it further into smaller task.

**Comment by dreacot** [comment]
@Blackdot-designer is this intended for the developers or the designers?

**Comment by Joshuaikenna9** [comment]
> 

The designers are currently working on this. But i believe it would be up for implementation by the developers when the designers are done. @dreacot

**Comment by Joshuaikenna9** [comment]
> This task from my POV is too bulky…
> 
> I already started work on the V2 layout design. When this is done, we intend to break it further into smaller task.

All these are V2 layout designs

**Comment by Sirmorrison** [comment]
This no longer applies
