### ISSUE TITLE
Crash on Navigation to staking

### ISSUE THREAD

**Issue by crux25** [planetdecred/godcr#976]
On the current master master branch Navigating to Staking crashes godcr. See log below.
`2022-06-09 14:16:16.584 [INF] DLWL: Loaded 2 wallets
2022-06-09 14:16:18.017 [INF] DLWL: Opened wallet
2022-06-09 14:16:19.199 [INF] DLWL: Opened wallet
panic: runtime error: integer divide by zero

goroutine 40 [running]:
github.com/planetdecred/godcr/ui/decredmaterial.(*MultiLayerProgressBar).progressBarLayout.func2(0xbf)
	/home/amos/go/src/github.com/planetdecred/godcr/ui/decredmaterial/progressbar.go:155 +0x6d
github.com/planetdecred/godcr/ui/decredmaterial.(*MultiLayerProgressBar).progressBarLayout.func3({{{0x0, 0x0}, {0x212, 0xf41e5}}, {0x3f800000, 0x3f800000}, {0x1d81dc0, 0xc0000ff8e8}, {0xc0a09a969f1c6a80, 0xe65ee2f75, ...}, ...})
	/home/amos/go/src/github.com/planetdecred/godcr/ui/decredmaterial/progressbar.go:162 +0x43
gioui.org/layout.Flex.Layout({0x5, 0x0, 0x0, 0x0}, {{{0x212, 0x0}, {0x212, 0xf41e5}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/amos/go/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/decredmaterial.(*MultiLayerProgressBar).progressBarLayout(0xc000093aa0, {{{0x212, 0x0}, {0x212, 0xf41e5}}, {0x3f800000, 0x3f800000}, {0x1d81dc0, 0xc0000ff8e8}, {0xc0a09a969f1c6a80, ...}, ...})
	/home/amos/go/src/github.com/planetdecred/godcr/ui/decredmaterial/progressbar.go:160 +0x391
gioui.org/layout.Inset.Layout({0x11c, 0x0, 0x4fd99e0, 0xc0}, {{{0x212, 0x0}, {0x212, 0xf41e5}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/amos/go/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/layout.go:139 +0x3b6
github.com/planetdecred/godcr/ui/decredmaterial.(*MultiLayerProgressBar).Layout.func1({{{0x212, 0x0}, {0x212, 0xf41ea}}, {0x3f800000, 0x3f800000}, {0x1d81dc0, 0xc0000ff8e8}, {0xc0a09a969f1c6a80, 0xe65ee2f75, ...}, ...})
	/home/amos/go/src/github.com/planetdecred/godcr/ui/decredmaterial/progressbar.go:182 +0x98
gioui.org/layout.Flex.Layout({0x0, 0x3d, 0x3b, 0xc0}, {{{0x212, 0x0}, {0x212, 0xf41fc}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/amos/go/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/decredmaterial.(*MultiLayerProgressBar).Layout(0xc000093aa0, {{{0x212, 0x0}, {0x212, 0xf41fc}}, {0x3f800000, 0x3f800000}, {0x1d81dc0, 0xc0000ff8e8}, {0xc0a09a969f1c6a80, ...}, ...}, ...)
	/home/amos/go/src/github.com/planetdecred/godcr/ui/decredmaterial/progressbar.go:179 +0x175
github.com/planetdecred/godcr/ui/page/staking.(*Page).walletBalanceLayout.func1.2({{{0x212, 0x0}, {0x212, 0xf41fc}}, {0x3f800000, 0x3f800000}, {0x1d81dc0, 0xc0000ff8e8}, {0xc0a09a969f1c6a80, 0xe65ee2f75, ...}, ...})
	/home/amos/go/src/github.com/planetdecred/godcr/ui/page/staking/balance_layout.go:73 +0x345
gioui.org/layout.Flex.Layout({0xb0, 0x14, 0x4a, 0xc0}, {{{0x212, 0x0}, {0x212, 0xf4218}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/amos/go/pkg/mod/gioui.org@v0.0.0-20220601100144-a896a467ecae/layout/flex.go:99 +0xdb5
github.com/planetdecred/godcr/ui/page/staking.(*Page).walletBalanceLayout.func1({{{0x212, 0x0}, {0x212, 0xf4218}}, {0x3f800000, 0x3f800000}, {0x1d81dc0, 0xc0000ff8e8}, {0xc0a09a969f1c6a80, 0xe65ee2f75, ...}, ...})
`

**Comment by Sirmorrison** [comment]
This will be looked into with the v2 redesign.
