### ISSUE TITLE
V2 more page update

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#986]
<img width="381" alt="image" src="https://user-images.githubusercontent.com/27733432/174015477-e748b054-4466-475c-8d34-ea3ef8740b0a.png">

**Comment by dreacot** [comment]
UI wise, I can't notice any difference between this page and what's on master.

Except this issue is requesting the debug menu be removed from the item list

![Screenshot from 2022-06-22 10-37-25](https://user-images.githubusercontent.com/25265396/174997100-70da7c03-34a5-45ee-b73e-5ab1831c74ee.png)
