### ISSUE TITLE
App level security page.

### ISSUE THREAD

**Issue by Sirmorrison** [planetdecred/godcr#993]
Add the app level security page layout. The scope of the issue is just the layout only and not component functionality.

<img width="411" alt="image" src="https://user-images.githubusercontent.com/27733432/174019094-c70def84-0521-4fa5-914f-c01c1dbdfbdc.png">

**Comment by JustinBeBoy** [comment]
This is layout nothing to change from old, it just has text to change

**Comment by dreacot** [comment]
there's an update layout here https://www.figma.com/file/e0cYaAzkXyXXPY00v23cQY/GoDCR-%26-DCRMobile?node-id=4659%3A182253
