### ISSUE TITLE
buttons don't respond to click events on the governance page

### ISSUE THREAD

**Issue by dreacot** [planetdecred/godcr#997]
since the app package was implemented, buttons on the governance sub pages(Proposals, Consensus), no longer respond to click events.

**Comment by devchoplife** [comment]
This is also experienced on the restore page

**Comment by Sirmorrison** [comment]
https://user-images.githubusercontent.com/27733432/174556528-a64839d7-1026-41ca-a056-4f6bda1b5684.mov

i am currently able to navigate between the pages on master.
What exactly is challenge?

**Comment by dreacot** [comment]
I'm referring to the buttons contained in the subpages, such as the info icon button, voting dashboard button.....
